City Simulation: CityPlanner Class Reference
CityPlanner Class Reference
Manages infrastructure construction and transport system integration.
#include <CityPlanner.h>
Public Member Functions
~CityPlanner ()
Destructor.
Infrastructure * constructInfrastructure (InfrastructureBuilder &builder)
Constructs new infrastructure.
double estimateProjectCost (InfrastructureBuilder &builder)
void clearProjects ()
const std::vector< Infrastructure * > & getCompletedProjects () const
ModernTransport * integrateTransportSystem (const std::string &type)
ModernTransport * adaptLegacyTransport (LegacyTransportSystem *legacySystem)
const std::vector< ModernTransport * > & getTransportSystems () const
Private Attributes
std::vector< Infrastructure * > completedProjects
List of completed infrastructure projects.
std::vector< ModernTransport * > transportSystems
List of transport systems.
Detailed Description
Manages infrastructure construction and transport system integration.
Coordinates between different infrastructure builders and transport systems
See also
InfrastructureBuilder
ModernTransport
TransportSystemAdapter
Definition at line 26 of file CityPlanner.h.
Constructor & Destructor Documentation
~CityPlanner()
CityPlanner::~CityPlanner () inline
Destructor.
Cleans up all projects and transport systems
Definition at line 43 of file CityPlanner.h.
                    {
         for (auto project : completedProjects) {
             delete project;
         }
         for (auto transport : transportSystems) {
             delete transport;
         }
     }
References completedProjects, and transportSystems.
Member Function Documentation
adaptLegacyTransport()
ModernTransport* CityPlanner::adaptLegacyTransport (LegacyTransportSystem * legacySystem) inline
Definition at line 96 of file CityPlanner.h.
{
         ModernTransport* adapted = TransportFactory::adaptLegacyTransport(legacySystem);
         if (adapted) {
             transportSystems.push_back(adapted);
         }
         return adapted;
     }
References TransportFactory::adaptLegacyTransport(), and transportSystems.
clearProjects()
void CityPlanner::clearProjects () inline
Definition at line 77 of file CityPlanner.h.
{
         for (auto project : completedProjects) {
             delete project;
         }
         completedProjects.clear();
     }
References completedProjects.
constructInfrastructure()
Infrastructure* CityPlanner::constructInfrastructure (InfrastructureBuilder & builder) inline
Constructs new infrastructure.
Parameters
builder Infrastructure builder to use
Returns
Infrastructure* Pointer to completed infrastructure
Exceptions
std::runtime_error If build is invalid
Definition at line 58 of file CityPlanner.h.
{
         builder.reset();
         builder.BuildFoundation();
         builder.BuildStructure();
         builder.BuildFinishing();
         if (!builder.isValidBuild()) {
             throw std::runtime_error("Invalid build state!");
         }
         Infrastructure* result = builder.GetResult();
         completedProjects.push_back(result);
         return result;
     }
References InfrastructureBuilder::BuildFinishing(), InfrastructureBuilder::BuildFoundation(), InfrastructureBuilder::BuildStructure(), completedProjects, InfrastructureBuilder::GetResult(), InfrastructureBuilder::isValidBuild(), and InfrastructureBuilder::reset().
estimateProjectCost()
double CityPlanner::estimateProjectCost (InfrastructureBuilder & builder) inline
Definition at line 73 of file CityPlanner.h.
{
         return builder.estimateTotalCost();
     }
References InfrastructureBuilder::estimateTotalCost().
getCompletedProjects()
const std::vector<Infrastructure*>& CityPlanner::getCompletedProjects () const inline
Definition at line 84 of file CityPlanner.h.
{
         return completedProjects;
     }
References completedProjects.
getTransportSystems()
const std::vector<ModernTransport*>& CityPlanner::getTransportSystems () const inline
Definition at line 104 of file CityPlanner.h.
{
         return transportSystems;
     }
References transportSystems.
Referenced by testTransportSystemAdaptation().
integrateTransportSystem()
ModernTransport* CityPlanner::integrateTransportSystem (const std::string & type) inline
Definition at line 88 of file CityPlanner.h.
{
         ModernTransport* transport = TransportFactory::createTransport(type);
         if (transport) {
             transportSystems.push_back(transport);
         }
         return transport;
     }
References TransportFactory::createTransport(), and transportSystems.
Referenced by testTransportSystemAdaptation().
Member Data Documentation
completedProjects
std::vector<Infrastructure*> CityPlanner::completedProjects private
List of completed infrastructure projects.
Definition at line 31 of file CityPlanner.h.
Referenced by clearProjects(), constructInfrastructure(), getCompletedProjects(), and ~CityPlanner().
transportSystems
std::vector<ModernTransport*> CityPlanner::transportSystems private
List of transport systems.
Definition at line 36 of file CityPlanner.h.
Referenced by adaptLegacyTransport(), getTransportSystems(), integrateTransportSystem(), and ~CityPlanner().
The documentation for this class was generated from the following file:
CityPlanner.h