City Simulation: UtilityNetworkBuilder Class Reference
UtilityNetworkBuilder Class Reference
Builder class that constructs UtilityNetwork objects.
#include <UtilityNetworkBuilder.h>
Public Member Functions
UtilityNetworkBuilder ()
Default constructor.
~UtilityNetworkBuilder ()
Destructor.
void reset () override
Resets the builder to initial state.
void BuildFoundation () override
Builds the foundation of the utility network.
void BuildStructure () override
Builds the main structure.
void BuildFinishing () override
Applies finishing touches to the infrastructure.
Infrastructure * GetResult () override
Returns the constructed Infrastructure object.
bool isValidBuild () const override
Checks if the current build configuration is valid.
double estimateTotalCost () const override
Estimates the total cost of the infrastructure.
Public Member Functions inherited from InfrastructureBuilder
virtual ~InfrastructureBuilder ()=default
Virtual destructor.
Private Member Functions
void validateState () const
Validates the internal state of the builder.
Additional Inherited Members
Protected Attributes inherited from InfrastructureBuilder
Infrastructure * product = nullptr
Pointer to the infrastructure being built.
Detailed Description
Builder class that constructs UtilityNetwork objects.
Implements the InfrastructureBuilder interface to create utility networks
Definition at line 14 of file UtilityNetworkBuilder.h.
Constructor & Destructor Documentation
UtilityNetworkBuilder()
UtilityNetworkBuilder::UtilityNetworkBuilder () inline
Default constructor.
Initializes the builder and creates a new empty product
Definition at line 31 of file UtilityNetworkBuilder.h.
 { reset(); }
References reset().
~UtilityNetworkBuilder()
UtilityNetworkBuilder::~UtilityNetworkBuilder () inline
Destructor.
Cleans up the product if it exists
Definition at line 37 of file UtilityNetworkBuilder.h.
{
         if (product) {
             delete product;
         }
     }
References InfrastructureBuilder::product.
Member Function Documentation
BuildFinishing()
void UtilityNetworkBuilder::BuildFinishing () inline override virtual
Applies finishing touches to the infrastructure.
Implements InfrastructureBuilder.
Definition at line 71 of file UtilityNetworkBuilder.h.
{
         validateState();
         std::string current = product->getDescription();
         product->setDescription(current + " - Completed");
         product->setCost(product->getCost() + 400000.0);
         static_cast<UtilityNetwork*>(product)->setCompleted(true);
     }
References Infrastructure::getCost(), Infrastructure::getDescription(), InfrastructureBuilder::product, Infrastructure::setCost(), Infrastructure::setDescription(), and validateState().
BuildFoundation()
void UtilityNetworkBuilder::BuildFoundation () inline override virtual
Builds the foundation of the utility network.
Sets up basic description and initial cost
Implements InfrastructureBuilder.
Definition at line 58 of file UtilityNetworkBuilder.h.
{
         reset();
         product->setDescription("Utility Network Foundation");
         product->setCost(800000.0);
     }
References InfrastructureBuilder::product, reset(), Infrastructure::setCost(), and Infrastructure::setDescription().
Referenced by testIntegratedSystem().
BuildStructure()
void UtilityNetworkBuilder::BuildStructure () inline override virtual
Builds the main structure.
Implements InfrastructureBuilder.
Definition at line 64 of file UtilityNetworkBuilder.h.
{
         validateState();
         std::string current = product->getDescription();
         product->setDescription(current + " with Utility Infrastructure");
         product->setCost(product->getCost() + 1500000.0);
     }
References Infrastructure::getCost(), Infrastructure::getDescription(), InfrastructureBuilder::product, Infrastructure::setCost(), Infrastructure::setDescription(), and validateState().
Referenced by testIntegratedSystem().
estimateTotalCost()
double UtilityNetworkBuilder::estimateTotalCost () const inline override virtual
Estimates the total cost of the infrastructure.
Returns
Estimated cost in currency units
Implements InfrastructureBuilder.
Definition at line 90 of file UtilityNetworkBuilder.h.
{
         return 2700000.0;
     }
Referenced by testIntegratedSystem().
GetResult()
Infrastructure* UtilityNetworkBuilder::GetResult () inline override virtual
Returns the constructed Infrastructure object.
Returns
Pointer to the constructed Infrastructure object
Implements InfrastructureBuilder.
Definition at line 79 of file UtilityNetworkBuilder.h.
{
         validateState();
         Infrastructure* result = product;
         product = nullptr;
         return result;
     }
References InfrastructureBuilder::product, and validateState().
Referenced by testIntegratedSystem().
isValidBuild()
bool UtilityNetworkBuilder::isValidBuild () const inline override virtual
Checks if the current build configuration is valid.
Returns
true if the build is valid, false otherwise
Implements InfrastructureBuilder.
Definition at line 86 of file UtilityNetworkBuilder.h.
{
         return product && product->isValid();
     }
References Infrastructure::isValid(), and InfrastructureBuilder::product.
reset()
void UtilityNetworkBuilder::reset () inline override virtual
Resets the builder to initial state.
Deletes existing product and creates a new empty UtilityNetwork
Implements InfrastructureBuilder.
Definition at line 47 of file UtilityNetworkBuilder.h.
{
         if (product) {
             delete product;
         }
         product = new UtilityNetwork();
     }
References InfrastructureBuilder::product.
Referenced by BuildFoundation(), and UtilityNetworkBuilder().
validateState()
void UtilityNetworkBuilder::validateState () const inline private
Validates the internal state of the builder.
Exceptions
std::runtime_error if no product exists
Definition at line 20 of file UtilityNetworkBuilder.h.
{
         if (!product) {
             throw std::runtime_error("No product exists!");
         }
     }
References InfrastructureBuilder::product.
Referenced by BuildFinishing(), BuildStructure(), and GetResult().
The documentation for this class was generated from the following file:
UtilityNetworkBuilder.h