City Simulation: BaseBuilding Class Reference
BaseBuilding Class Reference abstract
Abstract base class defining core building interface.
#include <BaseBuilding.h>
Public Member Functions
virtual std::string getDescription () const =0
Get building description.
virtual double getCost () const =0
Get building cost.
virtual ~BaseBuilding ()=default
Virtual destructor.
Detailed Description
Abstract base class defining core building interface.
Provides pure virtual functions for basic building operations
Definition at line 15 of file BaseBuilding.h.
Constructor & Destructor Documentation
~BaseBuilding()
virtual BaseBuilding::~BaseBuilding () virtual default
Virtual destructor.
Member Function Documentation
getCost()
virtual double BaseBuilding::getCost () const pure virtual
Get building cost.
Returns
double Cost of the building
Implemented in Residential, Landmarks, Industrial, Commercial, BuildingUpgrade, and Building.
getDescription()
virtual std::string BaseBuilding::getDescription () const pure virtual
Get building description.
Returns
std::string Description of the building
Implemented in SecurityUpgrade, Residential, Landmarks, Industrial, Commercial, CapacityUpgrade, and BuildingUpgrade.
Referenced by BuildingUpgrade::getDescription(), CapacityUpgrade::getDescription(), and SecurityUpgrade::getDescription().
The documentation for this class was generated from the following file:
BaseBuilding.h