City Simulation: PublicTransit Class Reference
PublicTransit Class Reference
Represents public transit infrastructure in a city system.
#include <PublicTransit.h>
Public Member Functions
PublicTransit ()
Default constructor Initializes a new public transit project with empty description, zero cost, and incomplete status.
void setDescription (const std::string &desc) override
Sets the description of the public transit project.
std::string getDescription () const override
Gets the description of the public transit project.
double getCost () const override
Gets the total cost of the project.
void setCost (double value) override
Sets the cost of the project.
std::string getType () const override
Gets the type of infrastructure.
bool isValid () const override
Validates the public transit project.
Infrastructure * clone () const override
Creates a deep copy of the public transit project.
void setCompleted (bool completed)
Sets the completion status of the project.
bool getCompleted () const
Gets the completion status of the project.
void displayInfo () const override
Displays detailed information about the public transit project.
Public Member Functions inherited from Infrastructure
virtual ~Infrastructure ()=default
Virtual destructor.
Private Attributes
std::string description
Description of the public transit project.
double cost
Total cost of the project.
bool isCompleted
Completion status of the project.
Detailed Description
Represents public transit infrastructure in a city system.
This class manages public transit infrastructure projects, including their description, cost, and completion status.
Definition at line 18 of file PublicTransit.h.
Constructor & Destructor Documentation
PublicTransit()
PublicTransit::PublicTransit () inline
Default constructor Initializes a new public transit project with empty description, zero cost, and incomplete status.
Definition at line 30 of file PublicTransit.h.
 : description(""), cost(0.0), isCompleted(false) {}
Referenced by clone().
Member Function Documentation
clone()
Infrastructure* PublicTransit::clone () const inline override virtual
Creates a deep copy of the public transit project.
Returns
Pointer to the cloned object
Implements Infrastructure.
Definition at line 74 of file PublicTransit.h.
{
         PublicTransit* copy = new PublicTransit();
         copy->description = this->description;
         copy->cost = this->cost;
         copy->isCompleted = this->isCompleted;
         return copy;
     }
References cost, description, isCompleted, and PublicTransit().
displayInfo()
void PublicTransit::displayInfo () const inline override virtual
Displays detailed information about the public transit project.
Outputs type, description, cost, status, and validation information
Implements Infrastructure.
Definition at line 99 of file PublicTransit.h.
{
         std::cout << "\n=== Public Transit Infrastructure ===" << std::endl
                   << "Type: " << getType() << std::endl
                   << "Description: " << description << std::endl
                   << "Cost: $" << std::fixed << std::setprecision(2) << cost << std::endl
                   << "Status: " << (isCompleted ? "Completed" : "In Progress") << std::endl
                   << "Validation: " << (isValid() ? "Valid" : "Invalid") << std::endl;
     }
References cost, description, getType(), isCompleted, and isValid().
Referenced by testIntegratedSystem().
getCompleted()
bool PublicTransit::getCompleted () const inline
Gets the completion status of the project.
Returns
The current completion status
Definition at line 92 of file PublicTransit.h.
 { return isCompleted; }
References isCompleted.
getCost()
double PublicTransit::getCost () const inline override virtual
Gets the total cost of the project.
Returns
The project cost
Implements Infrastructure.
Definition at line 48 of file PublicTransit.h.
 { return cost; }
References cost.
getDescription()
std::string PublicTransit::getDescription () const inline override virtual
Gets the description of the public transit project.
Returns
The project description
Implements Infrastructure.
Definition at line 42 of file PublicTransit.h.
 { return description; }
References description.
getType()
std::string PublicTransit::getType () const inline override virtual
Gets the type of infrastructure.
Returns
String "PublicTransit"
Implements Infrastructure.
Definition at line 60 of file PublicTransit.h.
 { return "PublicTransit"; }
Referenced by displayInfo().
isValid()
bool PublicTransit::isValid () const inline override virtual
Validates the public transit project.
Returns
true if the project has a non-empty description and positive cost
Implements Infrastructure.
Definition at line 66 of file PublicTransit.h.
{
         return !description.empty() && cost > 0;
     }
References cost, and description.
Referenced by displayInfo().
setCompleted()
void PublicTransit::setCompleted (bool completed) inline
Sets the completion status of the project.
Parameters
completed The completion status to set
Definition at line 86 of file PublicTransit.h.
 { isCompleted = completed; }
References isCompleted.
setCost()
void PublicTransit::setCost (double value) inline override virtual
Sets the cost of the project.
Parameters
value The cost to set
Implements Infrastructure.
Definition at line 54 of file PublicTransit.h.
 { cost = value; }
References cost.
setDescription()
void PublicTransit::setDescription (const std::string & desc) inline override virtual
Sets the description of the public transit project.
Parameters
desc The description to set
Implements Infrastructure.
Definition at line 36 of file PublicTransit.h.
 { description = desc; }
References description.
Member Data Documentation
cost
double PublicTransit::cost private
Total cost of the project.
Definition at line 21 of file PublicTransit.h.
Referenced by clone(), displayInfo(), getCost(), isValid(), and setCost().
description
std::string PublicTransit::description private
Description of the public transit project.
Definition at line 20 of file PublicTransit.h.
Referenced by clone(), displayInfo(), getDescription(), isValid(), and setDescription().
isCompleted
bool PublicTransit::isCompleted private
Completion status of the project.
Definition at line 22 of file PublicTransit.h.
Referenced by clone(), displayInfo(), getCompleted(), and setCompleted().
The documentation for this class was generated from the following file:
PublicTransit.h