City Simulation: Building Class Reference
Building Class Reference abstract
Abstract base class representing a building in the city.
#include <Building.h>
Public Member Functions
virtual double calculateTax () const
virtual double calculateTotalTax () const
Building (const std::string &name, double area, int capacity, double cost)
virtual ~Building ()
void setCost (long double cost)
void print (int indent=0) const override
Prints the component details.
void incrementOccupancy ()
void upgradeSecurity ()
void upgradeEnergyEfficiency ()
void upgradeCapacity ()
void setSecurityLevel (int level)
void setEnergyLevel (int level)
void setCapacityLevel (int level)
int getSecurityLevel () const
int getEnergyLevel () const
int getCapacityLevel () const
void setState (BuildingState *newState)
std::string getState () const
virtual void setMaxCapacity (int capacity)=0
virtual int getMaxCapacity () const =0
virtual double getFloorArea () const =0
virtual double getCost () const =0
Get building cost.
std::string getName () const override
Gets the component name.
void add (CityComponent *component) override
Adds a child component.
void remove (CityComponent *component) override
Removes a child component.
void setParentNeighborhood (Neighborhood *neighborhood)
Neighborhood * getParentNeighborhood () const
double getResourceRequirement (const std::string &resourceType) const
void receiveResource (const std::string &resource, int amount) override
Receive resource allocation.
int getResourceLevel (const std::string &resource) const override
Get current resource level.
bool needsResource (const std::string &resource) const override
Check if resource is needed.
void setResourceRequirement (const std::string &resource, int amount)
Public Member Functions inherited from CityComponent
virtual ~CityComponent ()=default
Virtual destructor.
virtual double getPopulation () const
Gets the component population.
virtual double getArea () const
Gets the component area.
virtual std::vector< CityComponent * > getComponents () const
Gets child components.
virtual CityComponent * findComponent (const std::string &name)
Finds a component by name.
virtual std::string getBuildingType () const
Gets the building type.
Public Member Functions inherited from BaseBuilding
virtual std::string getDescription () const =0
Get building description.
virtual ~BaseBuilding ()=default
Virtual destructor.
Public Member Functions inherited from ResourceConsumer
virtual ~ResourceConsumer ()=default
Virtual destructor.
Static Public Member Functions
static void cleanup ()
Static Public Attributes
static std::vector< Building * > buildings
Protected Attributes
std::string buildingType
std::string name
double floorArea
int maxCapacity
int currentOccupancy = 0
bool maintenanceNeeded
double energyUsage
long double Cost
int securityLevel = 1
int capacityLevel = 1
int energyLevel = 1
Neighborhood * parentNeighborhood
std::unordered_map< std::string, int > resourceLevels
Protected Attributes inherited from CityComponent
double population = 0.0
Component population.
double area = 0.0
Component area.
Private Attributes
BuildingTax * buildingTax
BuildingState * state
std::unordered_map< std::string, double > resourceRequirements
Detailed Description
Abstract base class representing a building in the city.
Implements resource consumption, state management, and upgrades
See also
CityComponent
BaseBuilding
ResourceConsumer
Definition at line 32 of file Building.h.
Constructor & Destructor Documentation
Building()
Building::Building (const std::string & name, double area, int capacity, double cost)
Definition at line 11 of file Building.cpp.
     : name(name),maxCapacity(capacity),floorArea(area), currentOccupancy(0), maintenanceNeeded(false), energyUsage(0.0), Cost(cost), state(new Operational())
 {
     buildingTax = new BuildingTax();
     buildings.push_back(this);
     parentNeighborhood = nullptr;
 }
References buildings, buildingTax, and parentNeighborhood.
~Building()
Building::~Building () virtual
Definition at line 29 of file Building.cpp.
                     {
     auto it = std::find(buildings.begin(), buildings.end(), this);
     if (it != buildings.end()) {
         buildings.erase(it);
     }
     delete buildingTax;
     buildingTax = nullptr;
     delete state;
     state = nullptr;
 }
References buildings, buildingTax, and state.
Member Function Documentation
add()
void Building::add (CityComponent * component) inline override virtual
Adds a child component.
Parameters
component Pointer to component to add
Implements CityComponent.
Reimplemented in Residential, Industrial, Commercial, BuildingUpgrade, and Landmarks.
Definition at line 92 of file Building.h.
     {
         // Since Building is a leaf node in the Composite pattern,
         // it shouldn't support adding child components
         throw std::runtime_error("Cannot add components to a Building (Leaf node)");
     }
Referenced by BuildingUpgrade::add().
calculateTax()
double Building::calculateTax () const virtual
Definition at line 19 of file Building.cpp.
 {
     return buildingTax->calculateTax(Cost);
 }
References buildingTax, BuildingTax::calculateTax(), and Cost.
calculateTotalTax()
double Building::calculateTotalTax () const virtual
Definition at line 24 of file Building.cpp.
 {
     return buildingTax->calculateTotalTax();
 }
References buildingTax, and BuildingTax::calculateTotalTax().
Referenced by testBuildingTaxSystem(), and testIntegratedSystem().
cleanup()
static void Building::cleanup () inline static
Definition at line 116 of file Building.h.
{
         buildings.clear(); // Clear the vector but don't delete the objects
     }
References buildings.
Referenced by main().
getCapacityLevel()
int Building::getCapacityLevel () const inline
Definition at line 76 of file Building.h.
 { return capacityLevel; }
References capacityLevel.
Referenced by CapacityUpgrade::CapacityUpgrade(), and print().
getCost()
virtual double Building::getCost () const pure virtual
Get building cost.
Returns
double Cost of the building
Implements BaseBuilding.
Implemented in Residential, Landmarks, Industrial, Commercial, and BuildingUpgrade.
Referenced by CapacityUpgrade::applyUpgrade(), EnergyEfficiencyUpgrade::applyUpgrade(), SecurityUpgrade::applyUpgrade(), BuildingUpgrade::getCost(), print(), and testBuildingUpgrades().
getEnergyLevel()
int Building::getEnergyLevel () const inline
Definition at line 75 of file Building.h.
 { return energyLevel; }
References energyLevel.
Referenced by EnergyEfficiencyUpgrade::EnergyEfficiencyUpgrade(), and print().
getFloorArea()
virtual double Building::getFloorArea () const pure virtual
Implemented in Residential, Landmarks, Industrial, Commercial, and BuildingUpgrade.
Referenced by BuildingUpgrade::getFloorArea(), and print().
getMaxCapacity()
virtual int Building::getMaxCapacity () const pure virtual
Implemented in Residential, Landmarks, Industrial, Commercial, and BuildingUpgrade.
Referenced by BuildingUpgrade::getMaxCapacity(), and print().
getName()
std::string Building::getName () const inline override virtual
Gets the component name.
Returns
String containing the component name
Implements CityComponent.
Definition at line 88 of file Building.h.
     {
         return name;
     }
References name.
Referenced by Commercial::getDescription(), Industrial::getDescription(), Landmarks::getDescription(), and Residential::getDescription().
getParentNeighborhood()
Neighborhood* Building::getParentNeighborhood () const inline
Definition at line 111 of file Building.h.
     {
         return parentNeighborhood;
     }
References parentNeighborhood.
getResourceLevel()
int Building::getResourceLevel (const std::string & resource) const inline override virtual
Get current resource level.
Parameters
resource Type of resource
Returns
int Current amount of resource
Implements ResourceConsumer.
Definition at line 139 of file Building.h.
{
         auto it = resourceLevels.find(resource);
         return (it != resourceLevels.end()) ? it->second : 0;
     }
References resourceLevels.
getResourceRequirement()
double Building::getResourceRequirement (const std::string & resourceType) const inline
Definition at line 120 of file Building.h.
{
         auto it = resourceRequirements.find(resourceType);
         if (it != resourceRequirements.end()) {
             return it->second;
         }
         return 0.0;
     }
References resourceRequirements.
getSecurityLevel()
int Building::getSecurityLevel () const inline
Definition at line 74 of file Building.h.
 { return securityLevel; }
References securityLevel.
Referenced by print(), and SecurityUpgrade::SecurityUpgrade().
getState()
std::string Building::getState () const
Definition at line 47 of file Building.cpp.
 {
     return state->getState();
 }
References BuildingState::getState(), and state.
Referenced by print(), and testBuildingStateSystem().
incrementOccupancy()
void Building::incrementOccupancy ()
Definition at line 75 of file Building.cpp.
 {
     if (currentOccupancy < maxCapacity)
     {
         currentOccupancy++;
     }
 }
References currentOccupancy, and maxCapacity.
Referenced by CitizenPrototype::setBuilding().
needsResource()
bool Building::needsResource (const std::string & resource) const inline override virtual
Check if resource is needed.
Parameters
resource Type of resource
Returns
bool True if resource is needed
Implements ResourceConsumer.
Definition at line 144 of file Building.h.
{
         auto req = resourceRequirements.find(resource);
         auto level = resourceLevels.find(resource);
         // Need resource if we have a requirement and current level is less than required
         if (req != resourceRequirements.end()) {
             int currentLevel = (level != resourceLevels.end()) ? level->second : 0;
             return currentLevel < req->second;
         }
         return false;
     }
References resourceLevels, and resourceRequirements.
print()
void Building::print (int indent = 0) const override virtual
Prints the component details.
Parameters
indent Indentation level for hierarchical display
Implements CityComponent.
Definition at line 83 of file Building.cpp.
 {
     std::cout << "\n===" << name << " Details ===\n";
     std::string indentation(indent, ' ');
     std::cout << std::string(indent, ' ') << "===" << name << " Details ===\n"
               << std::string(indent, ' ') << "  Type: " << getBuildingType() << "\n"
               << std::string(indent, ' ') << "  Floor Area: " << getFloorArea() << " sq m\n"
               << std::string(indent, ' ') << "  Capacity: " << currentOccupancy << "/"
               << getMaxCapacity() << "\n"
               << std::string(indent, ' ') << "  Cost: R" << std::fixed
               << std::setprecision(2) << getCost() << "\n"
               << std::string(indent, ' ') << "  Security Level: " << getSecurityLevel() << "\n"
               << std::string(indent, ' ') << "  Energy Efficiency: " << getEnergyLevel() << "\n"
               << std::string(indent, ' ') << "  Capacity Level: " << getCapacityLevel() << "\n"
               << std::string(indent, ' ') << "  State: " << getState() << "\n";
 }
References currentOccupancy, CityComponent::getBuildingType(), getCapacityLevel(), getCost(), getEnergyLevel(), getFloorArea(), getMaxCapacity(), getSecurityLevel(), getState(), and name.
Referenced by Retired::performTask(), Student::performTask(), Worker::performTask(), testBuildingUpgrades(), testCompositePatternNew(), and testIntegratedSystem().
receiveResource()
void Building::receiveResource (const std::string & resource, int amount) inline override virtual
Receive resource allocation.
Parameters
resource Type of resource
amount Quantity received
Implements ResourceConsumer.
Definition at line 135 of file Building.h.
{
         resourceLevels[resource] += amount;
     }
References resourceLevels.
remove()
void Building::remove (CityComponent * component) inline override virtual
Removes a child component.
Parameters
component Pointer to component to remove
Implements CityComponent.
Reimplemented in Residential, Industrial, Commercial, BuildingUpgrade, and Landmarks.
Definition at line 99 of file Building.h.
     {
         // Since Building is a leaf node in the Composite pattern,
         // it shouldn't support removing child components
         throw std::runtime_error("Cannot remove components from a Building (Leaf node)");
     }
Referenced by BuildingUpgrade::remove().
setCapacityLevel()
void Building::setCapacityLevel (int level) inline
Definition at line 72 of file Building.h.
 { capacityLevel = level; }
References capacityLevel.
Referenced by CapacityUpgrade::applyUpgrade().
setCost()
void Building::setCost (long double cost)
Definition at line 52 of file Building.cpp.
 {
     Cost = cost;
 }
References Cost.
Referenced by CapacityUpgrade::applyUpgrade(), EnergyEfficiencyUpgrade::applyUpgrade(), and SecurityUpgrade::applyUpgrade().
setEnergyLevel()
void Building::setEnergyLevel (int level) inline
Definition at line 71 of file Building.h.
 { energyLevel = level; }
References energyLevel.
Referenced by EnergyEfficiencyUpgrade::applyUpgrade().
setMaxCapacity()
virtual void Building::setMaxCapacity (int capacity) pure virtual
Implemented in Residential, Landmarks, Industrial, Commercial, and BuildingUpgrade.
Referenced by BuildingUpgrade::setMaxCapacity().
setParentNeighborhood()
void Building::setParentNeighborhood (Neighborhood * neighborhood) inline
Definition at line 106 of file Building.h.
     {
         parentNeighborhood = neighborhood;
     }
References parentNeighborhood.
setResourceRequirement()
void Building::setResourceRequirement (const std::string & resource, int amount) inline
Definition at line 156 of file Building.h.
{
         resourceRequirements[resource] = amount;
     }
References resourceRequirements.
Referenced by ConcreteBuildingFactory::createBuilding(), and testMediatorPattern().
setSecurityLevel()
void Building::setSecurityLevel (int level) inline
Definition at line 70 of file Building.h.
 { securityLevel = level; }
References securityLevel.
Referenced by SecurityUpgrade::applyUpgrade().
setState()
void Building::setState (BuildingState * newState)
Definition at line 41 of file Building.cpp.
 {
     delete state; // Clean up old state
     state = newState;
 }
References state.
Referenced by testBuildingStateSystem().
upgradeCapacity()
void Building::upgradeCapacity ()
Definition at line 69 of file Building.cpp.
 {
     CapacityUpgrade capacityUpgrade(this);
     capacityUpgrade.applyUpgrade();
 }
References CapacityUpgrade::applyUpgrade().
upgradeEnergyEfficiency()
void Building::upgradeEnergyEfficiency ()
Definition at line 63 of file Building.cpp.
 {
     EnergyEfficiencyUpgrade energyUpgrade(this);
     energyUpgrade.applyUpgrade();
 }
References EnergyEfficiencyUpgrade::applyUpgrade().
upgradeSecurity()
void Building::upgradeSecurity ()
Definition at line 57 of file Building.cpp.
 {
     SecurityUpgrade securityUpgrade(this);
     securityUpgrade.applyUpgrade();
 }
References SecurityUpgrade::applyUpgrade().
Member Data Documentation
buildings
std::vector<Building *> Building::buildings inline static
Definition at line 56 of file Building.h.
Referenced by Building(), BuildingTax::calculateTotalTax(), cleanup(), and ~Building().
buildingTax
BuildingTax* Building::buildingTax private
Definition at line 35 of file Building.h.
Referenced by Building(), calculateTax(), calculateTotalTax(), and ~Building().
buildingType
std::string Building::buildingType protected
Definition at line 40 of file Building.h.
Referenced by Commercial::Commercial(), Commercial::getBuildingType(), Industrial::getBuildingType(), Landmarks::getBuildingType(), Residential::getBuildingType(), Industrial::Industrial(), Landmarks::Landmarks(), and Residential::Residential().
capacityLevel
int Building::capacityLevel = 1 protected
Definition at line 49 of file Building.h.
Referenced by getCapacityLevel(), and setCapacityLevel().
Cost
long double Building::Cost protected
Definition at line 47 of file Building.h.
Referenced by calculateTax(), Commercial::getCost(), Industrial::getCost(), Landmarks::getCost(), Residential::getCost(), and setCost().
currentOccupancy
int Building::currentOccupancy = 0 protected
Definition at line 44 of file Building.h.
Referenced by incrementOccupancy(), and print().
energyLevel
int Building::energyLevel = 1 protected
Definition at line 50 of file Building.h.
Referenced by getEnergyLevel(), and setEnergyLevel().
energyUsage
double Building::energyUsage protected
Definition at line 46 of file Building.h.
floorArea
double Building::floorArea protected
Definition at line 42 of file Building.h.
Referenced by Commercial::getFloorArea(), Industrial::getFloorArea(), Landmarks::getFloorArea(), and Residential::getFloorArea().
maintenanceNeeded
bool Building::maintenanceNeeded protected
Definition at line 45 of file Building.h.
maxCapacity
int Building::maxCapacity protected
Definition at line 43 of file Building.h.
Referenced by Commercial::getMaxCapacity(), Industrial::getMaxCapacity(), Landmarks::getMaxCapacity(), Residential::getMaxCapacity(), incrementOccupancy(), Commercial::setMaxCapacity(), Industrial::setMaxCapacity(), Landmarks::setMaxCapacity(), and Residential::setMaxCapacity().
name
std::string Building::name protected
Definition at line 41 of file Building.h.
Referenced by getName(), and print().
parentNeighborhood
Neighborhood* Building::parentNeighborhood protected
Definition at line 52 of file Building.h.
Referenced by Building(), getParentNeighborhood(), and setParentNeighborhood().
resourceLevels
std::unordered_map<std::string, int> Building::resourceLevels protected
Definition at line 53 of file Building.h.
Referenced by getResourceLevel(), needsResource(), and receiveResource().
resourceRequirements
std::unordered_map<std::string, double> Building::resourceRequirements private
Definition at line 37 of file Building.h.
Referenced by getResourceRequirement(), needsResource(), and setResourceRequirement().
securityLevel
int Building::securityLevel = 1 protected
Definition at line 48 of file Building.h.
Referenced by getSecurityLevel(), and setSecurityLevel().
state
BuildingState* Building::state private
Definition at line 36 of file Building.h.
Referenced by getState(), setState(), and ~Building().
The documentation for this class was generated from the following files:
Building.h
Building.cpp