City Simulation: ConcreteBuildingFactory Class Reference
ConcreteBuildingFactory Class Reference
Concrete implementation of the BuildingFactory interface.
#include <ConcreteBuildingFactory.h>
Public Member Functions
Building * createBuilding (const std::string &type, const std::string &name, double area, int capacity, double cost, const std::string &districtName="Default District", const std::string &neighborhoodName="Default Neighborhood") const override
Creates a new building of the specified type.
Public Member Functions inherited from BuildingFactory
virtual ~BuildingFactory ()=default
Virtual destructor for proper cleanup of derived classes.
Detailed Description
Concrete implementation of the BuildingFactory interface.
This factory creates different types of buildings (Residential, Commercial, Industrial, Landmarks) with predefined resource requirements and parameters.
Definition at line 18 of file ConcreteBuildingFactory.h.
Member Function Documentation
createBuilding()
Building* ConcreteBuildingFactory::createBuilding (const std::string & type, const std::string & name, double area, int capacity, double cost, const std::string & districtName = "Default District", const std::string & neighborhoodName = "Default Neighborhood") const inline override virtual
Creates a new building of the specified type.
Parameters
type Type of building to create ("Residential", "Commercial", "Industrial", "Landmark")
name Name of the building
area Floor area of the building in square meters
capacity Maximum occupancy of the building
cost Construction cost of the building
districtName Name of the district where building will be located (optional)
neighborhoodName Name of the neighborhood where building will be located (optional)
Returns
Building* Pointer to the newly created building
Exceptions
std::invalid_argument if building type is invalid
Implements BuildingFactory.
Definition at line 33 of file ConcreteBuildingFactory.h.
{
         Building* building = nullptr;
         // Create the building based on type
         if (type == "Residential") {
             building = new Residential(name, area, capacity, cost, 100);
             building->setResourceRequirement("electricity", 150); // Match utility resource name
             building->setResourceRequirement("water", 100);
         }
         else if (type == "Commercial") {
             building = new Commercial(name, area, capacity, cost);
             building->setResourceRequirement("electricity", 300);
             building->setResourceRequirement("water", 200);
         }
         else if (type == "Industrial") {
             building = new Industrial(name, area, capacity, cost);
         }
         else if (type == "Landmarks") {
             building = new Landmarks(name, area, capacity, cost);
         }
         if (building) {
             CityResourceDistribution::getInstance()->registerBuilding(building);
             // Get or create city (singleton)
             City* city = City::getInstance();
             // Get or create district
             CityComponent* districtComponent = city->findOrCreateDistrict(districtName);
             District* district = dynamic_cast<District*>(districtComponent);
             if (!district) {
                 delete building;
                 throw std::runtime_error("Failed to create or cast district");
             }
             // Get or create neighborhood
             CityComponent* neighborhoodComponent = district->findOrCreateNeighborhood(neighborhoodName);
             Neighborhood* neighborhood = dynamic_cast<Neighborhood*>(neighborhoodComponent);
             if (!neighborhood) {
                 delete building;
                 throw std::runtime_error("Failed to create or cast neighborhood");
             }
             // Add building to neighborhood
             neighborhood->add(building);
         }
         return building;
     }
References Neighborhood::add(), City::findOrCreateDistrict(), District::findOrCreateNeighborhood(), City::getInstance(), CityResourceDistribution::getInstance(), CityResourceDistribution::registerBuilding(), and Building::setResourceRequirement().
Referenced by demostratePrototypePattern(), testBuildingStateSystem(), testBuildingTaxSystem(), testBuildingUpgrades(), testCompositePatternNew(), testIntegratedSystem(), and testMediatorPattern().
The documentation for this class was generated from the following file:
ConcreteBuildingFactory.h