City Simulation: PublicTransitBuilder Class Reference
PublicTransitBuilder Class Reference
Builder class for constructing PublicTransit objects.
#include <PublicTransitBuilder.h>
Public Member Functions
PublicTransitBuilder ()
Default constructor Initializes the builder and creates a new product.
~PublicTransitBuilder ()
Destructor Cleans up any allocated product.
void reset () override
Resets the builder to initial state Creates a new PublicTransit object.
void BuildFoundation () override
Builds the foundation of the public transit infrastructure Sets initial description and base cost.
void BuildStructure () override
Builds the main structure of the public transit infrastructure Adds to the description and increases cost.
void BuildFinishing () override
Applies finishing touches to the public transit infrastructure Completes the description, adds final costs, and marks as completed.
Infrastructure * GetResult () override
Returns the constructed product and resets the builder.
bool isValidBuild () const override
Checks if the current build is valid.
double estimateTotalCost () const override
Estimates the total cost of the project.
Public Member Functions inherited from InfrastructureBuilder
virtual ~InfrastructureBuilder ()=default
Virtual destructor.
Private Member Functions
void validateState () const
Validates the current state of the builder.
Additional Inherited Members
Protected Attributes inherited from InfrastructureBuilder
Infrastructure * product = nullptr
Pointer to the infrastructure being built.
Detailed Description
Builder class for constructing PublicTransit objects.
Implements the Builder pattern to construct PublicTransit infrastructure in a step-by-step manner.
Definition at line 18 of file PublicTransitBuilder.h.
Constructor & Destructor Documentation
PublicTransitBuilder()
PublicTransitBuilder::PublicTransitBuilder () inline
Default constructor Initializes the builder and creates a new product.
Definition at line 35 of file PublicTransitBuilder.h.
 { reset(); }
References reset().
~PublicTransitBuilder()
PublicTransitBuilder::~PublicTransitBuilder () inline
Destructor Cleans up any allocated product.
Definition at line 41 of file PublicTransitBuilder.h.
{
         if (product) {
             delete product;
         }
     }
References InfrastructureBuilder::product.
Member Function Documentation
BuildFinishing()
void PublicTransitBuilder::BuildFinishing () inline override virtual
Applies finishing touches to the public transit infrastructure Completes the description, adds final costs, and marks as completed.
Implements InfrastructureBuilder.
Definition at line 83 of file PublicTransitBuilder.h.
{
         validateState();
         std::string current = product->getDescription();
         product->setDescription(current + " - Completed");
         product->setCost(product->getCost() + 500000.0);
         static_cast<PublicTransit*>(product)->setCompleted(true);
     }
References Infrastructure::getCost(), Infrastructure::getDescription(), InfrastructureBuilder::product, Infrastructure::setCost(), Infrastructure::setDescription(), and validateState().
Referenced by testIntegratedSystem().
BuildFoundation()
void PublicTransitBuilder::BuildFoundation () inline override virtual
Builds the foundation of the public transit infrastructure Sets initial description and base cost.
Implements InfrastructureBuilder.
Definition at line 62 of file PublicTransitBuilder.h.
{
         reset();
         product->setDescription("Public Transit Foundation");
         product->setCost(1000000.0);
     }
References InfrastructureBuilder::product, reset(), Infrastructure::setCost(), and Infrastructure::setDescription().
Referenced by testIntegratedSystem().
BuildStructure()
void PublicTransitBuilder::BuildStructure () inline override virtual
Builds the main structure of the public transit infrastructure Adds to the description and increases cost.
Implements InfrastructureBuilder.
Definition at line 72 of file PublicTransitBuilder.h.
{
         validateState();
         std::string current = product->getDescription();
         product->setDescription(current + " with Transit Infrastructure");
         product->setCost(product->getCost() + 2000000.0);
     }
References Infrastructure::getCost(), Infrastructure::getDescription(), InfrastructureBuilder::product, Infrastructure::setCost(), Infrastructure::setDescription(), and validateState().
Referenced by testIntegratedSystem().
estimateTotalCost()
double PublicTransitBuilder::estimateTotalCost () const inline override virtual
Estimates the total cost of the project.
Returns
Estimated total cost (3.5 million)
Implements InfrastructureBuilder.
Definition at line 114 of file PublicTransitBuilder.h.
{
         return 3500000.0; // Base estimation
     }
Referenced by testIntegratedSystem().
GetResult()
Infrastructure* PublicTransitBuilder::GetResult () inline override virtual
Returns the constructed product and resets the builder.
Returns
Pointer to the completed Infrastructure object
Implements InfrastructureBuilder.
Definition at line 95 of file PublicTransitBuilder.h.
{
         validateState();
         Infrastructure* result = product;
         product = nullptr;
         return result;
     }
References InfrastructureBuilder::product, and validateState().
Referenced by testIntegratedSystem().
isValidBuild()
bool PublicTransitBuilder::isValidBuild () const inline override virtual
Checks if the current build is valid.
Returns
true if the product exists and is valid
Implements InfrastructureBuilder.
Definition at line 106 of file PublicTransitBuilder.h.
{
         return product && product->isValid();
     }
References Infrastructure::isValid(), and InfrastructureBuilder::product.
reset()
void PublicTransitBuilder::reset () inline override virtual
Resets the builder to initial state Creates a new PublicTransit object.
Implements InfrastructureBuilder.
Definition at line 51 of file PublicTransitBuilder.h.
{
         if (product) {
             delete product;
         }
         product = new PublicTransit();
     }
References InfrastructureBuilder::product.
Referenced by BuildFoundation(), PublicTransitBuilder(), and testIntegratedSystem().
validateState()
void PublicTransitBuilder::validateState () const inline private
Validates the current state of the builder.
Exceptions
std::runtime_error if no product exists
Definition at line 24 of file PublicTransitBuilder.h.
{
         if (!product) {
             throw std::runtime_error("No product exists!");
         }
     }
References InfrastructureBuilder::product.
Referenced by BuildFinishing(), BuildStructure(), and GetResult().
The documentation for this class was generated from the following file:
PublicTransitBuilder.h