City Simulation: RoadNetwork Class Reference
RoadNetwork Class Reference
Represents road network infrastructure in a city system.
#include <RoadNetwork.h>
Public Member Functions
RoadNetwork ()
Default constructor Initializes a new road network with empty description, zero cost, and incomplete status.
void setDescription (const std::string &desc) override
Sets the description of the road network.
std::string getDescription () const override
Gets the description of the road network.
double getCost () const override
Gets the total cost of the network.
void setCost (double value) override
Sets the cost of the network.
std::string getType () const override
Gets the type of infrastructure.
bool isValid () const override
Validates the road network.
Infrastructure * clone () const override
Creates a deep copy of the road network.
void setCompleted (bool completed)
Sets the completion status of the network.
bool getCompleted () const
Gets the completion status of the network.
void displayInfo () const override
Displays detailed information about the road network.
Public Member Functions inherited from Infrastructure
virtual ~Infrastructure ()=default
Virtual destructor.
Private Attributes
std::string description
Description of the road network.
double cost
Total cost of the network.
bool isCompleted
Completion status of the network.
Detailed Description
Represents road network infrastructure in a city system.
This class manages road network infrastructure projects, including their description, cost, and completion status.
Definition at line 18 of file RoadNetwork.h.
Constructor & Destructor Documentation
RoadNetwork()
RoadNetwork::RoadNetwork () inline
Default constructor Initializes a new road network with empty description, zero cost, and incomplete status.
Definition at line 30 of file RoadNetwork.h.
 : description(""), cost(0.0), isCompleted(false) {}
Referenced by clone().
Member Function Documentation
clone()
Infrastructure* RoadNetwork::clone () const inline override virtual
Creates a deep copy of the road network.
Returns
Pointer to the cloned object
Implements Infrastructure.
Definition at line 74 of file RoadNetwork.h.
{
         RoadNetwork* copy = new RoadNetwork();
         copy->description = this->description;
         copy->cost = this->cost;
         copy->isCompleted = this->isCompleted;
         return copy;
     }
References cost, description, isCompleted, and RoadNetwork().
displayInfo()
void RoadNetwork::displayInfo () const inline override virtual
Displays detailed information about the road network.
Outputs type, description, cost, status, and validation information
Implements Infrastructure.
Definition at line 99 of file RoadNetwork.h.
{
         std::cout << "\n=== Road Network Infrastructure ===" << std::endl
                   << "Type: " << getType() << std::endl
                   << "Description: " << description << std::endl
                   << "Cost: $" << std::fixed << std::setprecision(2) << cost << std::endl
                   << "Status: " << (isCompleted ? "Completed" : "In Progress") << std::endl
                   << "Validation: " << (isValid() ? "Valid" : "Invalid") << std::endl;
     }
References cost, description, getType(), isCompleted, and isValid().
Referenced by testIntegratedSystem().
getCompleted()
bool RoadNetwork::getCompleted () const inline
Gets the completion status of the network.
Returns
The current completion status
Definition at line 92 of file RoadNetwork.h.
 { return isCompleted; }
References isCompleted.
getCost()
double RoadNetwork::getCost () const inline override virtual
Gets the total cost of the network.
Returns
The network cost
Implements Infrastructure.
Definition at line 48 of file RoadNetwork.h.
 { return cost; }
References cost.
getDescription()
std::string RoadNetwork::getDescription () const inline override virtual
Gets the description of the road network.
Returns
The network description
Implements Infrastructure.
Definition at line 42 of file RoadNetwork.h.
 { return description; }
References description.
getType()
std::string RoadNetwork::getType () const inline override virtual
Gets the type of infrastructure.
Returns
String "RoadNetwork"
Implements Infrastructure.
Definition at line 60 of file RoadNetwork.h.
 { return "RoadNetwork"; }
Referenced by displayInfo().
isValid()
bool RoadNetwork::isValid () const inline override virtual
Validates the road network.
Returns
true if the network has a non-empty description and positive cost
Implements Infrastructure.
Definition at line 66 of file RoadNetwork.h.
{
         return !description.empty() && cost > 0;
     }
References cost, and description.
Referenced by displayInfo().
setCompleted()
void RoadNetwork::setCompleted (bool completed) inline
Sets the completion status of the network.
Parameters
completed The completion status to set
Definition at line 86 of file RoadNetwork.h.
 { isCompleted = completed; }
References isCompleted.
setCost()
void RoadNetwork::setCost (double value) inline override virtual
Sets the cost of the network.
Parameters
value The cost to set
Implements Infrastructure.
Definition at line 54 of file RoadNetwork.h.
 { cost = value; }
References cost.
setDescription()
void RoadNetwork::setDescription (const std::string & desc) inline override virtual
Sets the description of the road network.
Parameters
desc The description to set
Implements Infrastructure.
Definition at line 36 of file RoadNetwork.h.
 { description = desc; }
References description.
Member Data Documentation
cost
double RoadNetwork::cost private
Total cost of the network.
Definition at line 21 of file RoadNetwork.h.
Referenced by clone(), displayInfo(), getCost(), isValid(), and setCost().
description
std::string RoadNetwork::description private
Description of the road network.
Definition at line 20 of file RoadNetwork.h.
Referenced by clone(), displayInfo(), getDescription(), isValid(), and setDescription().
isCompleted
bool RoadNetwork::isCompleted private
Completion status of the network.
Definition at line 22 of file RoadNetwork.h.
Referenced by clone(), displayInfo(), getCompleted(), and setCompleted().
The documentation for this class was generated from the following file:
RoadNetwork.h