City Simulation: Student Class Reference
Student Class Reference
Represents student citizens in the city.
#include <Student.h>
Public Member Functions
Student (int id, double salary)
Constructor.
~Student () override=default
Destructor.
Student (const Student &other)
Copy constructor.
CitizenPrototype * clone () const override
Clone the student.
const std::string getRole () const override
Get the role of the student.
void performTask () override
Perform the student's task.
void setSalary (double newSalary) override
Set the student's salary and part-time job status.
Public Member Functions inherited from CitizenPrototype
CitizenPrototype (int id, double salary)
Constructor.
virtual ~CitizenPrototype ()
Virtual destructor.
CitizenPrototype (const CitizenPrototype &other)
Copy constructor.
virtual double calculateTotalTax () const
virtual double calculateTax () const
int getID () const
void setID (int newID)
double getSalary () const
void setBuilding (Building *b)
Building * getBuilding () const
double getSatisfaction () const
void updateSatisfaction (double newSatisfaction)
Private Attributes
bool hasPartTimeJob
Flag indicating part-time job status.
Additional Inherited Members
Static Public Member Functions inherited from CitizenPrototype
static int getCitizenCount ()
static void cleanup ()
Static Public Attributes inherited from CitizenPrototype
static std::vector< CitizenPrototype * > citizens
static int citizenCount = 0
Protected Member Functions inherited from CitizenPrototype
CitizenPrototype & operator= (const CitizenPrototype &other)
Protected Attributes inherited from CitizenPrototype
int id
Citizen identification number.
double salary
Citizen's salary or income.
double satisfaction
Citizen's satisfaction level.
Building * building
Building where citizen is located.
IncomeTax * incomeTax
Tax calculator for citizen.
Detailed Description
Represents student citizens in the city.
Implements student-specific behaviors and attributes
See also
CitizenPrototype
Definition at line 16 of file Student.h.
Constructor & Destructor Documentation
Student() [1/2]
Student::Student (int id, double salary) inline
Constructor.
Parameters
id Citizen identification number
salary Initial salary
Definition at line 29 of file Student.h.
 : CitizenPrototype(id, salary), hasPartTimeJob(false) {}
Referenced by clone().
~Student()
Student::~Student () override default
Destructor.
Student() [2/2]
Student::Student (const Student & other) inline
Copy constructor.
Parameters
other Student to copy
Definition at line 40 of file Student.h.
 : CitizenPrototype(other), hasPartTimeJob(other.hasPartTimeJob) {}
Member Function Documentation
clone()
CitizenPrototype* Student::clone () const inline override virtual
Clone the student.
Returns
Student* Copy of the student
Implements CitizenPrototype.
Definition at line 46 of file Student.h.
{
         return new Student(*this);
     }
References Student().
getRole()
const std::string Student::getRole () const inline override virtual
Get the role of the student.
Returns
std::string Role of the student
Implements CitizenPrototype.
Definition at line 54 of file Student.h.
{
         return "Student";
     }
performTask()
void Student::performTask () inline override virtual
Perform the student's task.
Implements CitizenPrototype.
Definition at line 61 of file Student.h.
{
         std::cout << "Student #" << getID() << " is studying";
         if (hasPartTimeJob) {
             std::cout << " and working part-time";
         }
         if (getBuilding()) {
             std::cout << " in the ";
             getBuilding()->print();
         }
         std::cout << "\n";
     }
References CitizenPrototype::getBuilding(), CitizenPrototype::getID(), hasPartTimeJob, and Building::print().
setSalary()
void Student::setSalary (double newSalary) inline override virtual
Set the student's salary and part-time job status.
Parameters
newSalary New salary amount
Reimplemented from CitizenPrototype.
Definition at line 77 of file Student.h.
{
         if (newSalary > 0) {
             std::cout << "Student #" << getID() << " is primarily studying but has taken a part-time job with salary $"
                      << newSalary << std::endl;
             salary = newSalary;
             hasPartTimeJob = true;
         } else {
             std::cout << "Student #" << getID() << " is focusing fully on studies without a part-time job" << std::endl;
             salary = 0;
             hasPartTimeJob = false;
         }
     }
References CitizenPrototype::getID(), hasPartTimeJob, and CitizenPrototype::salary.
Member Data Documentation
hasPartTimeJob
bool Student::hasPartTimeJob private
Flag indicating part-time job status.
Definition at line 21 of file Student.h.
Referenced by performTask(), and setSalary().
The documentation for this class was generated from the following file:
Student.h