City Simulation: ConcreteCityStats Class Reference
ConcreteCityStats Class Reference
Concrete implementation of city statistics tracking.
#include <ConcreteCityStats.h>
Public Member Functions
ConcreteCityStats ()
Default constructor.
void setStats (double sat, double growth)
Sets and updates city statistics.
int getPopulation () const
Gets the current population.
double getSatisfaction () const
Gets the current satisfaction level.
double getEconomicGrowth () const
Gets the current economic growth rate.
Public Member Functions inherited from CityStats
virtual ~CityStats ()=default
Virtual destructor.
void attach (CityObserver *observer)
Registers a new observer.
void detach (CityObserver *observer)
Removes a registered observer.
Private Attributes
double satisfaction
Current citizen satisfaction level.
double economicGrowth
Current economic growth rate.
Additional Inherited Members
Protected Member Functions inherited from CityStats
void notify (int population, double satisfaction, double economicGrowth)
Notifies all observers of updates to city statistics.
Detailed Description
Concrete implementation of city statistics tracking.
Manages and updates various city metrics including satisfaction and economic growth
Definition at line 16 of file ConcreteCityStats.h.
Constructor & Destructor Documentation
ConcreteCityStats()
ConcreteCityStats::ConcreteCityStats () inline
Default constructor.
Initializes satisfaction and economic growth to 0.0
Definition at line 27 of file ConcreteCityStats.h.
 : satisfaction(0.0), economicGrowth(0.0) {}
Member Function Documentation
getEconomicGrowth()
double ConcreteCityStats::getEconomicGrowth () const inline
Gets the current economic growth rate.
Returns
Current economic growth rate
Definition at line 85 of file ConcreteCityStats.h.
 { return economicGrowth; }
References economicGrowth.
Referenced by testObserverPattern().
getPopulation()
int ConcreteCityStats::getPopulation () const inline
Gets the current population.
Returns
Current population count, minimum 0
Definition at line 67 of file ConcreteCityStats.h.
{
         if (CitizenPrototype::getCitizenCount() < 0) {
             return 0;
         }
         return CitizenPrototype::getCitizenCount();
     }
References CitizenPrototype::getCitizenCount().
Referenced by testObserverPattern().
getSatisfaction()
double ConcreteCityStats::getSatisfaction () const inline
Gets the current satisfaction level.
Returns
Current satisfaction percentage
Definition at line 79 of file ConcreteCityStats.h.
 { return satisfaction; }
References satisfaction.
Referenced by testObserverPattern().
setStats()
void ConcreteCityStats::setStats (double sat, double growth) inline
Sets and updates city statistics.
Parameters
sat Initial satisfaction value
growth Economic growth value
Calculates actual satisfaction based on citizen data if available
Definition at line 35 of file ConcreteCityStats.h.
     {
         int currentPopulation = CitizenPrototype::getCitizenCount();
         // For debugging
         std::cout << "Debug - Current citizen count: " << currentPopulation << "\n";
         std::cout << "Debug - Citizens vector size: " << CitizenPrototype::citizens.size() << "\n";
         double totalSatisfaction = 0.0;
         auto& citizens = CitizenPrototype::citizens;
         if (!citizens.empty()) {
             for (auto citizen : citizens) {
                 totalSatisfaction += citizen->getSatisfaction();
             }
             satisfaction = totalSatisfaction / citizens.size();
         } else {
             satisfaction = sat;
         }
         economicGrowth = growth;
         std::cout << "\nUpdating city stats with:"
                   << "\nPopulation: " << currentPopulation
                   << "\nSatisfaction: " << satisfaction << "%"
                   << "\nEconomic Growth: " << (economicGrowth * 100) << "%\n";
         notify(currentPopulation, satisfaction, economicGrowth);
     }
References CitizenPrototype::citizens, economicGrowth, CitizenPrototype::getCitizenCount(), CityStats::notify(), and satisfaction.
Referenced by testObserverPattern().
Member Data Documentation
economicGrowth
double ConcreteCityStats::economicGrowth private
Current economic growth rate.
Definition at line 20 of file ConcreteCityStats.h.
Referenced by getEconomicGrowth(), and setStats().
satisfaction
double ConcreteCityStats::satisfaction private
Current citizen satisfaction level.
Definition at line 19 of file ConcreteCityStats.h.
Referenced by getSatisfaction(), and setStats().
The documentation for this class was generated from the following file:
ConcreteCityStats.h