City Simulation: RoadNetworkBuilder Class Reference
RoadNetworkBuilder Class Reference
A builder class responsible for constructing road network infrastructure @inherits InfrastructureBuilder.
#include <RoadNetworkBuilder.h>
Public Member Functions
RoadNetworkBuilder ()
Default constructor that initializes a new road network.
~RoadNetworkBuilder ()
Destructor that ensures proper cleanup of the product.
void reset () override
Resets the builder to initial state with a new road network.
void BuildFoundation () override
Builds the foundation phase of the road network.
void BuildStructure () override
Builds the structural phase of the road network.
void BuildFinishing () override
Completes the finishing phase of the road network.
Infrastructure * GetResult () override
Returns the constructed road network.
bool isValidBuild () const override
Checks if the current build state is valid.
double estimateTotalCost () const override
Estimates the total cost of the road network construction.
Public Member Functions inherited from InfrastructureBuilder
virtual ~InfrastructureBuilder ()=default
Virtual destructor.
Private Member Functions
void validateState () const
Validates the current state of the builder.
Additional Inherited Members
Protected Attributes inherited from InfrastructureBuilder
Infrastructure * product = nullptr
Pointer to the infrastructure being built.
Detailed Description
A builder class responsible for constructing road network infrastructure @inherits InfrastructureBuilder.
This class implements the Builder pattern for creating road networks in a step-by-step manner, managing the construction process through foundation, structure, and finishing phases.
Definition at line 19 of file RoadNetworkBuilder.h.
Constructor & Destructor Documentation
RoadNetworkBuilder()
RoadNetworkBuilder::RoadNetworkBuilder () inline
Default constructor that initializes a new road network.
Definition at line 35 of file RoadNetworkBuilder.h.
 { reset(); }
References reset().
~RoadNetworkBuilder()
RoadNetworkBuilder::~RoadNetworkBuilder () inline
Destructor that ensures proper cleanup of the product.
Definition at line 40 of file RoadNetworkBuilder.h.
{
         if (product) {
             delete product;
         }
     }
References InfrastructureBuilder::product.
Member Function Documentation
BuildFinishing()
void RoadNetworkBuilder::BuildFinishing () inline override virtual
Completes the finishing phase of the road network.
Finalizes the construction and marks the network as completed
Implements InfrastructureBuilder.
Definition at line 84 of file RoadNetworkBuilder.h.
{
         validateState();
         std::string current = product->getDescription();
         product->setDescription(current + " - Completed");
         product->setCost(product->getCost() + 800000.0);
         static_cast<RoadNetwork*>(product)->setCompleted(true);
     }
References Infrastructure::getCost(), Infrastructure::getDescription(), InfrastructureBuilder::product, Infrastructure::setCost(), Infrastructure::setDescription(), and validateState().
Referenced by testIntegratedSystem().
BuildFoundation()
void RoadNetworkBuilder::BuildFoundation () inline override virtual
Builds the foundation phase of the road network.
Sets the initial description and base cost for the foundation
Implements InfrastructureBuilder.
Definition at line 61 of file RoadNetworkBuilder.h.
{
         reset();
         product->setDescription("Road Network Foundation");
         product->setCost(1500000.0);
     }
References InfrastructureBuilder::product, reset(), Infrastructure::setCost(), and Infrastructure::setDescription().
Referenced by testIntegratedSystem().
BuildStructure()
void RoadNetworkBuilder::BuildStructure () inline override virtual
Builds the structural phase of the road network.
Adds road infrastructure and updates the cost accordingly
Implements InfrastructureBuilder.
Definition at line 72 of file RoadNetworkBuilder.h.
{
         validateState();
         std::string current = product->getDescription();
         product->setDescription(current + " with Road Infrastructure");
         product->setCost(product->getCost() + 2500000.0);
     }
References Infrastructure::getCost(), Infrastructure::getDescription(), InfrastructureBuilder::product, Infrastructure::setCost(), Infrastructure::setDescription(), and validateState().
Referenced by testIntegratedSystem().
estimateTotalCost()
double RoadNetworkBuilder::estimateTotalCost () const inline override virtual
Estimates the total cost of the road network construction.
Returns
double The estimated total cost in currency units
Implements InfrastructureBuilder.
Definition at line 116 of file RoadNetworkBuilder.h.
{
         return 4800000.0;
     }
Referenced by testIntegratedSystem().
GetResult()
Infrastructure* RoadNetworkBuilder::GetResult () inline override virtual
Returns the constructed road network.
Returns
Infrastructure* Pointer to the completed infrastructure
Note
Transfers ownership of the product to the caller
Implements InfrastructureBuilder.
Definition at line 97 of file RoadNetworkBuilder.h.
{
         validateState();
         Infrastructure* result = product;
         product = nullptr;
         return result;
     }
References InfrastructureBuilder::product, and validateState().
Referenced by testIntegratedSystem().
isValidBuild()
bool RoadNetworkBuilder::isValidBuild () const inline override virtual
Checks if the current build state is valid.
Returns
bool True if the build is valid, false otherwise
Implements InfrastructureBuilder.
Definition at line 108 of file RoadNetworkBuilder.h.
{
         return product && product->isValid();
     }
References Infrastructure::isValid(), and InfrastructureBuilder::product.
reset()
void RoadNetworkBuilder::reset () inline override virtual
Resets the builder to initial state with a new road network.
Implements InfrastructureBuilder.
Definition at line 49 of file RoadNetworkBuilder.h.
{
         if (product) {
             delete product;
         }
         product = new RoadNetwork();
     }
References InfrastructureBuilder::product.
Referenced by BuildFoundation(), RoadNetworkBuilder(), and testIntegratedSystem().
validateState()
void RoadNetworkBuilder::validateState () const inline private
Validates the current state of the builder.
Exceptions
std::runtime_error if no product exists
Definition at line 25 of file RoadNetworkBuilder.h.
{
         if (!product) {
             throw std::runtime_error("No product exists!");
         }
     }
References InfrastructureBuilder::product.
Referenced by BuildFinishing(), BuildStructure(), and GetResult().
The documentation for this class was generated from the following file:
RoadNetworkBuilder.h