City Simulation: Retired Class Reference
Retired Class Reference
Represents a retired citizen in the city system.
#include <Retired.h>
Public Member Functions
Retired (int id, double pension)
Constructor for creating a retired citizen.
~Retired () override=default
Virtual destructor.
Retired (const Retired &other)
Copy constructor.
CitizenPrototype * clone () const override
Creates a clone of the retired citizen.
const std::string getRole () const override
Gets the role of the citizen.
void performTask () override
Performs the daily task of the retired citizen Outputs the current activity and location.
void setSalary (double newSalary) override
Attempts to set salary (not supported for retired citizens)
double getPension () const
Gets the pension amount.
Public Member Functions inherited from CitizenPrototype
CitizenPrototype (int id, double salary)
Constructor.
virtual ~CitizenPrototype ()
Virtual destructor.
CitizenPrototype (const CitizenPrototype &other)
Copy constructor.
virtual double calculateTotalTax () const
virtual double calculateTax () const
int getID () const
void setID (int newID)
double getSalary () const
void setBuilding (Building *b)
Building * getBuilding () const
double getSatisfaction () const
void updateSatisfaction (double newSatisfaction)
Additional Inherited Members
Static Public Member Functions inherited from CitizenPrototype
static int getCitizenCount ()
static void cleanup ()
Static Public Attributes inherited from CitizenPrototype
static std::vector< CitizenPrototype * > citizens
static int citizenCount = 0
Protected Member Functions inherited from CitizenPrototype
CitizenPrototype & operator= (const CitizenPrototype &other)
Protected Attributes inherited from CitizenPrototype
int id
Citizen identification number.
double salary
Citizen's salary or income.
double satisfaction
Citizen's satisfaction level.
Building * building
Building where citizen is located.
IncomeTax * incomeTax
Tax calculator for citizen.
Detailed Description
Represents a retired citizen in the city system.
This class manages retired citizens, including their pension and daily activities.
Definition at line 16 of file Retired.h.
Constructor & Destructor Documentation
Retired() [1/2]
Retired::Retired (int id, double pension) inline
Constructor for creating a retired citizen.
Parameters
id Unique identifier for the citizen
pension Monthly pension amount
Definition at line 23 of file Retired.h.
 : CitizenPrototype(id, pension) {}
Referenced by clone().
~Retired()
Retired::~Retired () override default
Virtual destructor.
Retired() [2/2]
Retired::Retired (const Retired & other) inline
Copy constructor.
Parameters
other The Retired object to copy from
Definition at line 34 of file Retired.h.
 : CitizenPrototype(other) {}
Member Function Documentation
clone()
CitizenPrototype* Retired::clone () const inline override virtual
Creates a clone of the retired citizen.
Returns
Pointer to the cloned object
Implements CitizenPrototype.
Definition at line 40 of file Retired.h.
{
         return new Retired(*this);
     }
References Retired().
getPension()
double Retired::getPension () const inline
Gets the pension amount.
Returns
Current pension amount
Definition at line 78 of file Retired.h.
{
         return getSalary();
     }
References CitizenPrototype::getSalary().
getRole()
const std::string Retired::getRole () const inline override virtual
Gets the role of the citizen.
Returns
String "Retired"
Implements CitizenPrototype.
Definition at line 48 of file Retired.h.
{
         return "Retired";
     }
performTask()
void Retired::performTask () inline override virtual
Performs the daily task of the retired citizen Outputs the current activity and location.
Implements CitizenPrototype.
Definition at line 56 of file Retired.h.
{
         std::cout << "Retired person #" << getID() << " is resting";
         if (getBuilding()) {
             std::cout << " in the ";
             getBuilding()->print();
         }
         std::cout << "\n";
     }
References CitizenPrototype::getBuilding(), CitizenPrototype::getID(), and Building::print().
setSalary()
void Retired::setSalary (double newSalary) inline override virtual
Attempts to set salary (not supported for retired citizens)
Parameters
newSalary The new salary value (ignored)
Reimplemented from CitizenPrototype.
Definition at line 69 of file Retired.h.
{
         std::cout << "You cannot modify pension for retired person #" << getID()
                  << ". Pension is fixed at $" << getSalary() << std::endl;
     }
References CitizenPrototype::getID(), and CitizenPrototype::getSalary().
The documentation for this class was generated from the following file:
Retired.h