City Simulation: District Class Reference
District Class Reference
Represents a city district containing neighborhoods.
#include <District.h>
Public Member Functions
District (const std::string &districtName)
Constructor.
~District ()
Destructor.
void add (CityComponent *component) override
Add neighborhood to district.
void remove (CityComponent *component) override
Remove neighborhood from district.
std::string getName () const override
Get district name.
std::vector< CityComponent * > getComponents () const override
Gets child components.
CityComponent * findComponent (const std::string &name) override
Finds a component by name.
CityComponent * findOrCreateNeighborhood (const std::string &neighborhoodName)
void print (int indent=0) const override
Prints the component details.
Public Member Functions inherited from CityComponent
virtual ~CityComponent ()=default
Virtual destructor.
virtual double getPopulation () const
Gets the component population.
virtual double getArea () const
Gets the component area.
virtual std::string getBuildingType () const
Gets the building type.
Private Attributes
std::string name
std::vector< CityComponent * > neighborhoods
Additional Inherited Members
Protected Attributes inherited from CityComponent
double population = 0.0
Component population.
double area = 0.0
Component area.
Detailed Description
Represents a city district containing neighborhoods.
Implements composite pattern for city organization
See also
CityComponent
Neighborhood
Definition at line 20 of file District.h.
Constructor & Destructor Documentation
District()
District::District (const std::string & districtName) inline
Constructor.
Parameters
districtName Name of the district
Definition at line 31 of file District.h.
 : name(districtName) {}
~District()
District::~District () inline
Destructor.
Cleans up all neighborhoods
Definition at line 37 of file District.h.
     {
         for (auto *neighborhood : neighborhoods)
         {
             delete neighborhood;
         }
         neighborhoods.clear();
     }
References neighborhoods.
Member Function Documentation
add()
void District::add (CityComponent * component) inline override virtual
Add neighborhood to district.
Parameters
component Neighborhood to add
Implements CityComponent.
Definition at line 50 of file District.h.
     {
         neighborhoods.push_back(component);
     }
References neighborhoods.
Referenced by findOrCreateNeighborhood().
findComponent()
CityComponent* District::findComponent (const std::string & name) inline override virtual
Finds a component by name.
Parameters
name Name of component to find
Returns
Pointer to found component or nullptr
Reimplemented from CityComponent.
Definition at line 82 of file District.h.
     {
         for (auto *neighborhood : neighborhoods)
         {
             if (neighborhood->getName() == name)
             {
                 return neighborhood;
             }
         }
         return nullptr;
     }
References name, and neighborhoods.
Referenced by findOrCreateNeighborhood(), and testCompositePatternNew().
findOrCreateNeighborhood()
CityComponent* District::findOrCreateNeighborhood (const std::string & neighborhoodName) inline
Definition at line 94 of file District.h.
     {
         CityComponent *existingNeighborhood = findComponent(neighborhoodName);
         if (existingNeighborhood)
         {
             return existingNeighborhood;
         }
         Neighborhood *newNeighborhood = new Neighborhood(neighborhoodName);
         add(newNeighborhood);
         return newNeighborhood;
     }
References add(), and findComponent().
Referenced by ConcreteBuildingFactory::createBuilding().
getComponents()
std::vector<CityComponent *> District::getComponents () const inline override virtual
Gets child components.
Returns
Vector of pointers to child components
Reimplemented from CityComponent.
Definition at line 77 of file District.h.
     {
         return neighborhoods;
     }
References neighborhoods.
getName()
std::string District::getName () const inline override virtual
Get district name.
Returns
std::string District name
Implements CityComponent.
Definition at line 72 of file District.h.
     {
         return name;
     }
References name.
print()
void District::print (int indent = 0) const inline override virtual
Prints the component details.
Parameters
indent Indentation level for hierarchical display
Implements CityComponent.
Definition at line 107 of file District.h.
     {
         std::string indentation(indent, ' ');
         std::cout << indentation << "District: " << name << "\n";
         for (auto *neighborhood : neighborhoods)
         {
             if (Neighborhood *n = dynamic_cast<Neighborhood *>(neighborhood))
             {
                 n->print(indent + 2);
             }
         }
     }
References name, and neighborhoods.
remove()
void District::remove (CityComponent * component) inline override virtual
Remove neighborhood from district.
Parameters
component Neighborhood to remove
Implements CityComponent.
Definition at line 59 of file District.h.
     {
         auto it = std::find(neighborhoods.begin(), neighborhoods.end(), component);
         if (it != neighborhoods.end())
         {
             neighborhoods.erase(it);
         }
     }
References neighborhoods.
Member Data Documentation
name
std::string District::name private
Definition at line 23 of file District.h.
Referenced by findComponent(), getName(), and print().
neighborhoods
std::vector<CityComponent *> District::neighborhoods private
Definition at line 24 of file District.h.
Referenced by add(), findComponent(), getComponents(), print(), remove(), and ~District().
The documentation for this class was generated from the following file:
District.h