City Simulation: LegacyTransportSystem Class Reference
LegacyTransportSystem Class Reference
Legacy transport system implementation.
#include <LegacyTransportSystem.h>
Public Member Functions
LegacyTransportSystem ()
Default constructor.
virtual ~LegacyTransportSystem ()
Virtual destructor.
virtual std::string operateOldTransport ()
Operates the legacy transport.
virtual int getOldCapacity () const
Gets the transport capacity.
virtual float getOldFuelUsage () const
Gets the fuel usage rate.
virtual const char * getVehicleClass () const
Gets the vehicle classification.
virtual float getRepairCosts () const
Gets the repair costs.
virtual int getServiceStatus () const
Gets the service status.
Protected Attributes
int oldCapacity
float fuelUsage
const char * vehicleClass
float repairCosts
int serviceStatus
Detailed Description
Legacy transport system implementation.
Provides basic functionality for managing legacy transport vehicles including capacity, fuel usage, and repair cost tracking
Definition at line 9 of file LegacyTransportSystem.h.
Constructor & Destructor Documentation
LegacyTransportSystem()
LegacyTransportSystem::LegacyTransportSystem () inline
Default constructor.
Initializes a legacy transport system with default values:
Capacity: 50
Fuel Usage: 20.0
Vehicle Class: "legacy"
Repair Costs: 2000.0
Service Status: 1
Definition at line 20 of file LegacyTransportSystem.h.
{
         oldCapacity = 50;
         fuelUsage = 20.0f;
         vehicleClass = "legacy";
         repairCosts = 2000.0f;
         serviceStatus = 1;
     }
References fuelUsage, oldCapacity, repairCosts, serviceStatus, and vehicleClass.
~LegacyTransportSystem()
virtual LegacyTransportSystem::~LegacyTransportSystem () inline virtual
Virtual destructor.
Definition at line 31 of file LegacyTransportSystem.h.
 {}
Member Function Documentation
getOldCapacity()
virtual int LegacyTransportSystem::getOldCapacity () const inline virtual
Gets the transport capacity.
Returns
int The capacity of the transport system
Definition at line 45 of file LegacyTransportSystem.h.
{
         return oldCapacity;
     }
References oldCapacity.
Referenced by TransportSystemAdapter::getPassengerCapacity(), testTransportSystemAdaptation(), and TransportSystemAdapter::updateModernAttributes().
getOldFuelUsage()
virtual float LegacyTransportSystem::getOldFuelUsage () const inline virtual
Gets the fuel usage rate.
Returns
float The fuel usage in units per operation
Definition at line 53 of file LegacyTransportSystem.h.
{
         return fuelUsage;
     }
References fuelUsage.
Referenced by TransportSystemAdapter::getFuelEfficiency(), testTransportSystemAdaptation(), and TransportSystemAdapter::updateModernAttributes().
getRepairCosts()
virtual float LegacyTransportSystem::getRepairCosts () const inline virtual
Gets the repair costs.
Returns
float The repair costs in monetary units
Definition at line 69 of file LegacyTransportSystem.h.
{
         return repairCosts;
     }
References repairCosts.
Referenced by TransportSystemAdapter::getMaintenanceCost(), testTransportSystemAdaptation(), and TransportSystemAdapter::updateModernAttributes().
getServiceStatus()
virtual int LegacyTransportSystem::getServiceStatus () const inline virtual
Gets the service status.
Returns
int The service status of the transport system
Definition at line 77 of file LegacyTransportSystem.h.
{
         return serviceStatus;
     }
References serviceStatus.
Referenced by TransportSystemAdapter::isOperational(), testTransportSystemAdaptation(), and TransportSystemAdapter::updateModernAttributes().
getVehicleClass()
virtual const char* LegacyTransportSystem::getVehicleClass () const inline virtual
Gets the vehicle classification.
Returns
const char* The vehicle class identifier
Definition at line 61 of file LegacyTransportSystem.h.
{
         return vehicleClass;
     }
References vehicleClass.
Referenced by TransportSystemAdapter::getTransportType(), testTransportSystemAdaptation(), and TransportSystemAdapter::updateModernAttributes().
operateOldTransport()
virtual std::string LegacyTransportSystem::operateOldTransport () inline virtual
Operates the legacy transport.
Returns
std::string Description of the operation with vehicle class
Definition at line 37 of file LegacyTransportSystem.h.
{
         return "Operating Legacy Transport: " + std::string(vehicleClass);
     }
References vehicleClass.
Referenced by TransportSystemAdapter::operationModernTransport(), and testTransportSystemAdaptation().
Member Data Documentation
fuelUsage
float LegacyTransportSystem::fuelUsage protected
Definition at line 83 of file LegacyTransportSystem.h.
Referenced by getOldFuelUsage(), and LegacyTransportSystem().
oldCapacity
int LegacyTransportSystem::oldCapacity protected
Definition at line 82 of file LegacyTransportSystem.h.
Referenced by getOldCapacity(), and LegacyTransportSystem().
repairCosts
float LegacyTransportSystem::repairCosts protected
Definition at line 85 of file LegacyTransportSystem.h.
Referenced by getRepairCosts(), and LegacyTransportSystem().
serviceStatus
int LegacyTransportSystem::serviceStatus protected
Definition at line 86 of file LegacyTransportSystem.h.
Referenced by getServiceStatus(), and LegacyTransportSystem().
vehicleClass
const char* LegacyTransportSystem::vehicleClass protected
Definition at line 84 of file LegacyTransportSystem.h.
Referenced by getVehicleClass(), LegacyTransportSystem(), and operateOldTransport().
The documentation for this class was generated from the following file:
LegacyTransportSystem.h