City Simulation: City Class Reference
City Class Reference
Singleton class representing the entire city structure.
#include <City.h>
Public Member Functions
City (const City &)=delete
City & operator= (const City &)=delete
~City ()
void add (CityComponent *component) override
Adds a child component.
void remove (CityComponent *component) override
Removes a child component.
std::string getName () const override
Gets the component name.
std::vector< CityComponent * > getComponents () const override
Gets child components.
CityComponent * findComponent (const std::string &name) override
Finds a component by name.
CityComponent * findOrCreateDistrict (const std::string &districtName)
void print (int indent=0) const
Prints the component details.
Public Member Functions inherited from CityComponent
virtual ~CityComponent ()=default
Virtual destructor.
virtual double getPopulation () const
Gets the component population.
virtual double getArea () const
Gets the component area.
virtual std::string getBuildingType () const
Gets the building type.
Static Public Member Functions
static City * getInstance ()
static void cleanup ()
Private Member Functions
City (const std::string &cityName="Default City")
Private Attributes
std::string name
std::vector< CityComponent * > districts
std::vector< CityComponent * > components
Static Private Attributes
static City * instance = nullptr
Additional Inherited Members
Protected Attributes inherited from CityComponent
double population = 0.0
Component population.
double area = 0.0
Component area.
Detailed Description
Singleton class representing the entire city structure.
Manages districts and overall city organization using composite pattern
See also
District
Neighborhood
CityComponent
Definition at line 23 of file City.h.
Constructor & Destructor Documentation
City() [1/2]
City::City (const std::string & cityName = "Default City") inline private
Definition at line 30 of file City.h.
 : name(cityName) {}
Referenced by getInstance().
City() [2/2]
City::City (const City &) delete
~City()
City::~City () inline
Definition at line 48 of file City.h.
             {
         for (auto* district : districts) {
             delete district;
         }
         districts.clear();
     }
References districts.
Member Function Documentation
add()
void City::add (CityComponent * component) inline override virtual
Adds a child component.
Parameters
component Pointer to component to add
Implements CityComponent.
Definition at line 55 of file City.h.
{
         districts.push_back(component);
     }
References districts.
Referenced by findOrCreateDistrict().
cleanup()
static void City::cleanup () inline static
Definition at line 43 of file City.h.
{
         delete instance;
         instance = nullptr;
     }
References instance.
Referenced by main(), and testCompositePatternNew().
findComponent()
CityComponent* City::findComponent (const std::string & name) inline override virtual
Finds a component by name.
Parameters
name Name of component to find
Returns
Pointer to found component or nullptr
Reimplemented from CityComponent.
Definition at line 76 of file City.h.
{
         for (auto* district : districts) {
             if (district->getName() == name) {
                 return district;
             }
         }
         return nullptr;
     }
References districts, and name.
Referenced by findOrCreateDistrict(), and testCompositePatternNew().
findOrCreateDistrict()
CityComponent* City::findOrCreateDistrict (const std::string & districtName) inline
Definition at line 86 of file City.h.
{
         // First try to find existing district
         CityComponent* existingDistrict = findComponent(districtName);
         if (existingDistrict) {
             return existingDistrict;
         }
         // If not found, create new district
         District* newDistrict = new District(districtName);
         add(newDistrict);
         return newDistrict;
     }
References add(), and findComponent().
Referenced by ConcreteBuildingFactory::createBuilding().
getComponents()
std::vector<CityComponent*> City::getComponents () const inline override virtual
Gets child components.
Returns
Vector of pointers to child components
Reimplemented from CityComponent.
Definition at line 71 of file City.h.
{
         return districts;
     }
References districts.
Referenced by testCompositePatternNew().
getInstance()
static City* City::getInstance () inline static
Definition at line 36 of file City.h.
{
         if (instance == nullptr) {
             instance = new City();
         }
         return instance;
     }
References City(), and instance.
Referenced by ConcreteBuildingFactory::createBuilding(), and testCompositePatternNew().
getName()
std::string City::getName () const inline override virtual
Gets the component name.
Returns
String containing the component name
Implements CityComponent.
Definition at line 66 of file City.h.
{
         return name;
     }
References name.
operator=()
City& City::operator= (const City &) delete
print()
void City::print (int indent = 0) const inline virtual
Prints the component details.
Parameters
indent Indentation level for hierarchical display
Implements CityComponent.
Definition at line 99 of file City.h.
{
         std::string indentation(indent, ' ');
         std::cout << indentation << "City: " << name << "\n";
         for (auto* district : districts) {
             if (District* d = dynamic_cast<District*>(district)) {
                 d->print(indent + 2);
             }
         }
     }
References districts, and name.
Referenced by testCompositePatternNew().
remove()
void City::remove (CityComponent * component) inline override virtual
Removes a child component.
Parameters
component Pointer to component to remove
Implements CityComponent.
Definition at line 59 of file City.h.
{
         auto it = std::find(districts.begin(), districts.end(), component);
         if (it != districts.end()) {
             districts.erase(it);
         }
     }
References districts.
Member Data Documentation
components
std::vector<CityComponent*> City::components private
Definition at line 28 of file City.h.
districts
std::vector<CityComponent*> City::districts private
Definition at line 27 of file City.h.
Referenced by add(), findComponent(), getComponents(), print(), remove(), and ~City().
instance
City * City::instance = nullptr static private
Definition at line 25 of file City.h.
Referenced by cleanup(), and getInstance().
name
std::string City::name private
Definition at line 26 of file City.h.
Referenced by findComponent(), getName(), and print().
The documentation for this class was generated from the following file:
City.h