City Simulation: CitizenPrototype Class Reference
CitizenPrototype Class Reference abstract
Abstract base class for different citizen types.
#include <CitizenPrototype.h>
Public Member Functions
CitizenPrototype (int id, double salary)
Constructor.
virtual ~CitizenPrototype ()
Virtual destructor.
CitizenPrototype (const CitizenPrototype &other)
Copy constructor.
virtual CitizenPrototype * clone () const =0
virtual const std::string getRole () const =0
virtual void performTask ()=0
virtual double calculateTotalTax () const
virtual double calculateTax () const
int getID () const
void setID (int newID)
double getSalary () const
virtual void setSalary (double newSalary)
void setBuilding (Building *b)
Building * getBuilding () const
double getSatisfaction () const
void updateSatisfaction (double newSatisfaction)
Static Public Member Functions
static int getCitizenCount ()
static void cleanup ()
Static Public Attributes
static std::vector< CitizenPrototype * > citizens
static int citizenCount = 0
Protected Member Functions
CitizenPrototype & operator= (const CitizenPrototype &other)
Protected Attributes
int id
Citizen identification number.
double salary
Citizen's salary or income.
double satisfaction
Citizen's satisfaction level.
Building * building
Building where citizen is located.
IncomeTax * incomeTax
Tax calculator for citizen.
Detailed Description
Abstract base class for different citizen types.
Implements prototype pattern for creating citizen instances
See also
Worker
Student
Retired
Definition at line 25 of file CitizenPrototype.h.
Constructor & Destructor Documentation
CitizenPrototype() [1/2]
CitizenPrototype::CitizenPrototype (int id, double salary)
Constructor.
Parameters
id Citizen identification number
salary Initial salary
Definition at line 8 of file CitizenPrototype.cpp.
     : id(id), salary(salary), satisfaction(0.0), building(nullptr), incomeTax(new IncomeTax())
 {
     citizens.push_back(this);
     ++citizenCount;
 }
References citizenCount, and citizens.
~CitizenPrototype()
CitizenPrototype::~CitizenPrototype () virtual
Virtual destructor.
Definition at line 15 of file CitizenPrototype.cpp.
{
     auto it = std::find(citizens.begin(), citizens.end(), this);
     if (it != citizens.end()) {
         citizens.erase(it);
     }
     delete incomeTax;
     incomeTax = nullptr;
 }
References citizens, and incomeTax.
CitizenPrototype() [2/2]
CitizenPrototype::CitizenPrototype (const CitizenPrototype & other)
Copy constructor.
Definition at line 24 of file CitizenPrototype.cpp.
     : id(other.id),
       salary(other.salary),
       satisfaction(other.satisfaction),
       building(other.building),
       incomeTax(other.incomeTax ? new IncomeTax(*other.incomeTax) : nullptr)
 {
     citizens.push_back(this);
     ++citizenCount;
 }
References citizenCount, and citizens.
Member Function Documentation
calculateTax()
double CitizenPrototype::calculateTax () const virtual
Definition at line 59 of file CitizenPrototype.cpp.
{
     return incomeTax ? incomeTax->calculateTax(salary) : 0.0;
 }
References IncomeTax::calculateTax(), incomeTax, and salary.
calculateTotalTax()
double CitizenPrototype::calculateTotalTax () const virtual
Definition at line 55 of file CitizenPrototype.cpp.
{
     return incomeTax ? incomeTax->calculateTotalTax() : 0.0;
 }
References IncomeTax::calculateTotalTax(), and incomeTax.
Referenced by testIncomeTaxSystem(), and testIntegratedSystem().
cleanup()
void CitizenPrototype::cleanup () static
Definition at line 63 of file CitizenPrototype.cpp.
{
     std::vector<CitizenPrototype*> temp;
     temp.swap(citizens);
     for (auto* citizen : temp) {
         delete citizen;
     }
 }
References citizens.
Referenced by demostratePrototypePattern().
clone()
virtual CitizenPrototype* CitizenPrototype::clone () const pure virtual
Implemented in Worker, Student, and Retired.
Referenced by demostratePrototypePattern().
getBuilding()
Building* CitizenPrototype::getBuilding () const inline
Definition at line 86 of file CitizenPrototype.h.
 { return building; }
References building.
Referenced by Retired::performTask(), Student::performTask(), and Worker::performTask().
getCitizenCount()
static int CitizenPrototype::getCitizenCount () inline static
Definition at line 91 of file CitizenPrototype.h.
{
         return citizens.size();
     }
References citizens.
Referenced by demostratePrototypePattern(), ConcreteCityStats::getPopulation(), ConcreteCityStats::setStats(), and PopulationGrowth::update().
getID()
int CitizenPrototype::getID () const inline
Definition at line 80 of file CitizenPrototype.h.
 { return id; }
References id.
Referenced by Retired::performTask(), Student::performTask(), Worker::performTask(), Retired::setSalary(), and Student::setSalary().
getRole()
virtual const std::string CitizenPrototype::getRole () const pure virtual
Implemented in Worker, Student, and Retired.
getSalary()
double CitizenPrototype::getSalary () const inline
Definition at line 82 of file CitizenPrototype.h.
 { return salary; }
References salary.
Referenced by Retired::getPension(), and Retired::setSalary().
getSatisfaction()
double CitizenPrototype::getSatisfaction () const inline
Definition at line 88 of file CitizenPrototype.h.
 { return satisfaction; }
References satisfaction.
operator=()
CitizenPrototype & CitizenPrototype::operator= (const CitizenPrototype & other) protected
Definition at line 42 of file CitizenPrototype.cpp.
{
     if (this != &other) {
         id = other.id;
         salary = other.salary;
         satisfaction = other.satisfaction;
         building = other.building;
         delete incomeTax;
         incomeTax = other.incomeTax ? new IncomeTax(*other.incomeTax) : nullptr;
     }
     return *this;
 }
References building, id, incomeTax, salary, and satisfaction.
performTask()
virtual void CitizenPrototype::performTask () pure virtual
Implemented in Worker, Student, and Retired.
setBuilding()
void CitizenPrototype::setBuilding (Building * b)
Definition at line 35 of file CitizenPrototype.cpp.
{
     building = b;
     if (building) {
         building->incrementOccupancy();
     }
 }
References building, and Building::incrementOccupancy().
setID()
void CitizenPrototype::setID (int newID) inline
Definition at line 81 of file CitizenPrototype.h.
 { id = newID; }
Referenced by demostratePrototypePattern().
setSalary()
virtual void CitizenPrototype::setSalary (double newSalary) inline virtual
Reimplemented in Student, and Retired.
Definition at line 83 of file CitizenPrototype.h.
 { salary = newSalary; }
References salary.
Referenced by demostratePrototypePattern().
updateSatisfaction()
void CitizenPrototype::updateSatisfaction (double newSatisfaction) inline
Definition at line 89 of file CitizenPrototype.h.
 { satisfaction = newSatisfaction; }
References satisfaction.
Member Data Documentation
building
Building* CitizenPrototype::building protected
Building where citizen is located.
Definition at line 45 of file CitizenPrototype.h.
Referenced by getBuilding(), operator=(), and setBuilding().
citizenCount
int CitizenPrototype::citizenCount = 0 static
Definition at line 54 of file CitizenPrototype.h.
Referenced by CitizenPrototype().
citizens
std::vector< CitizenPrototype * > CitizenPrototype::citizens static
Definition at line 53 of file CitizenPrototype.h.
Referenced by IncomeTax::calculateTotalTax(), CitizenPrototype(), cleanup(), demostratePrototypePattern(), getCitizenCount(), ConcreteCityStats::setStats(), CitizenSatisfaction::update(), and ~CitizenPrototype().
id
int CitizenPrototype::id protected
Citizen identification number.
Definition at line 30 of file CitizenPrototype.h.
Referenced by getID(), and operator=().
incomeTax
IncomeTax* CitizenPrototype::incomeTax protected
Tax calculator for citizen.
Definition at line 50 of file CitizenPrototype.h.
Referenced by calculateTax(), calculateTotalTax(), operator=(), and ~CitizenPrototype().
salary
double CitizenPrototype::salary protected
Citizen's salary or income.
Definition at line 35 of file CitizenPrototype.h.
Referenced by calculateTax(), getSalary(), operator=(), setSalary(), and Student::setSalary().
satisfaction
double CitizenPrototype::satisfaction protected
Citizen's satisfaction level.
Definition at line 40 of file CitizenPrototype.h.
Referenced by getSatisfaction(), operator=(), and updateSatisfaction().
The documentation for this class was generated from the following files:
CitizenPrototype.h
CitizenPrototype.cpp