City Simulation: CompositeGovDepartment Class Reference
CompositeGovDepartment Class Reference
A composite class that manages multiple government departments.
#include <CompositeGovDepartment.h>
Public Member Functions
void setCapital (double Capital) override
Sets the total capital for the composite department.
double getCapital () override
Gets the current total capital.
void distributeCapital ()
Distributes capital equally among all child departments.
double CalculateCapital (double Capital)
Calculates capital per department.
~CompositeGovDepartment () override=default
Virtual destructor.
void addDepartment (GovDepartment *department) override
Adds a new department to the composite.
void removeDepartment (GovDepartment *department) override
Removes a department from the composite.
Building * getBuilding () override
Gets the associated building.
size_t getDepartmentCount () const
Gets the total number of departments.
const std::vector< GovDepartment * > & getDepartments () const
Gets the vector of department pointers.
Public Member Functions inherited from GovDepartment
virtual ~GovDepartment ()=default
Virtual destructor.
Private Attributes
std::vector< GovDepartment * > departments
Container for child departments.
TaxationPolicy taxPolicy
Tax policy for the department.
double totalCapital = 0.0
Total capital available for distribution.
Detailed Description
A composite class that manages multiple government departments.
Implements the Composite design pattern to handle a collection of government departments and manage their capital distribution
Definition at line 20 of file CompositeGovDepartment.h.
Constructor & Destructor Documentation
~CompositeGovDepartment()
CompositeGovDepartment::~CompositeGovDepartment () override default
Virtual destructor.
Member Function Documentation
addDepartment()
void CompositeGovDepartment::addDepartment (GovDepartment * department) inline override virtual
Adds a new department to the composite.
Parameters
department Pointer to the department to add
Reimplemented from GovDepartment.
Definition at line 80 of file CompositeGovDepartment.h.
     {
         if (department)
         {
             departments.push_back(department);
             distributeCapital();
         }
     }
References departments, and distributeCapital().
Referenced by testIntegratedSystem().
CalculateCapital()
double CompositeGovDepartment::CalculateCapital (double Capital) inline
Calculates capital per department.
Parameters
Capital Total capital to be distributed
Returns
Amount of capital per department
Definition at line 66 of file CompositeGovDepartment.h.
     {
         return Capital / departments.size();
     }
References departments.
distributeCapital()
void CompositeGovDepartment::distributeCapital () inline
Distributes capital equally among all child departments.
Definition at line 49 of file CompositeGovDepartment.h.
     {
         if (departments.empty())
             return;
         double capitalPerDepartment = totalCapital / departments.size();
         for (GovDepartment *department : departments)
         {
             department->setCapital(capitalPerDepartment);
         }
     }
References departments, and totalCapital.
Referenced by addDepartment(), removeDepartment(), and testIntegratedSystem().
getBuilding()
Building* CompositeGovDepartment::getBuilding () inline override virtual
Gets the associated building.
Returns
nullptr as composite departments don't have direct building associations
Implements GovDepartment.
Definition at line 107 of file CompositeGovDepartment.h.
     {
         return nullptr;
     }
getCapital()
double CompositeGovDepartment::getCapital () inline override virtual
Gets the current total capital.
Returns
Current total capital amount
Implements GovDepartment.
Definition at line 41 of file CompositeGovDepartment.h.
     {
         return totalCapital;
     }
References totalCapital.
Referenced by testIntegratedSystem().
getDepartmentCount()
size_t CompositeGovDepartment::getDepartmentCount () const inline
Gets the total number of departments.
Returns
Number of departments in the composite
Definition at line 116 of file CompositeGovDepartment.h.
     {
         return departments.size();
     }
References departments.
getDepartments()
const std::vector<GovDepartment *>& CompositeGovDepartment::getDepartments () const inline
Gets the vector of department pointers.
Returns
Constant reference to the departments vector
Definition at line 125 of file CompositeGovDepartment.h.
     {
         return departments;
     }
References departments.
removeDepartment()
void CompositeGovDepartment::removeDepartment (GovDepartment * department) inline override virtual
Removes a department from the composite.
Parameters
department Pointer to the department to remove
Reimplemented from GovDepartment.
Definition at line 93 of file CompositeGovDepartment.h.
     {
         auto it = std::find(departments.begin(), departments.end(), department);
         if (it != departments.end())
         {
             departments.erase(it);
             distributeCapital();
         }
     }
References departments, and distributeCapital().
setCapital()
void CompositeGovDepartment::setCapital (double Capital) inline override virtual
Sets the total capital for the composite department.
Parameters
Capital The amount of capital to set
Implements GovDepartment.
Definition at line 32 of file CompositeGovDepartment.h.
     {
         totalCapital = Capital;
     }
References totalCapital.
Referenced by testIntegratedSystem().
Member Data Documentation
departments
std::vector<GovDepartment *> CompositeGovDepartment::departments private
Container for child departments.
Definition at line 23 of file CompositeGovDepartment.h.
Referenced by addDepartment(), CalculateCapital(), distributeCapital(), getDepartmentCount(), getDepartments(), and removeDepartment().
taxPolicy
TaxationPolicy CompositeGovDepartment::taxPolicy private
Tax policy for the department.
Definition at line 24 of file CompositeGovDepartment.h.
totalCapital
double CompositeGovDepartment::totalCapital = 0.0 private
Total capital available for distribution.
Definition at line 25 of file CompositeGovDepartment.h.
Referenced by distributeCapital(), getCapital(), and setCapital().
The documentation for this class was generated from the following file:
CompositeGovDepartment.h