City Simulation: CityStats Class Reference
CityStats Class Reference
Manages collection of city statistics observers.
#include <CityStats.h>
Public Member Functions
virtual ~CityStats ()=default
Virtual destructor.
void attach (CityObserver *observer)
Registers a new observer.
void detach (CityObserver *observer)
Removes a registered observer.
Protected Member Functions
void notify (int population, double satisfaction, double economicGrowth)
Notifies all observers of updates to city statistics.
Private Attributes
std::vector< CityObserver * > observers
Collection of registered observers.
Detailed Description
Manages collection of city statistics observers.
Implements the Subject role in the Observer pattern, maintaining a list of observers and notifying them of changes in city statistics.
Definition at line 17 of file CityStats.h.
Constructor & Destructor Documentation
~CityStats()
virtual CityStats::~CityStats () virtual default
Virtual destructor.
Member Function Documentation
attach()
void CityStats::attach (CityObserver * observer) inline
Registers a new observer.
Parameters
observer Pointer to observer to register
Definition at line 31 of file CityStats.h.
{
         if (observer != nullptr) {
             observers.push_back(observer);
         }
     }
References observers.
Referenced by testObserverPattern().
detach()
void CityStats::detach (CityObserver * observer) inline
Removes a registered observer.
Parameters
observer Pointer to observer to remove
Definition at line 41 of file CityStats.h.
{
         if (observer != nullptr) {
             observers.erase(
                 std::remove(observers.begin(), observers.end(), observer),
                 observers.end()
             );
         }
     }
References observers.
Referenced by testObserverPattern().
notify()
void CityStats::notify (int population, double satisfaction, double economicGrowth) inline protected
Notifies all observers of updates to city statistics.
Parameters
population Current city population
satisfaction Current satisfaction level
economicGrowth Current economic growth rate
Definition at line 57 of file CityStats.h.
{
         for (auto& observer : observers) {
             if (observer != nullptr) {
                 observer->update(population, satisfaction, economicGrowth);
             }
         }
     }
References observers.
Referenced by ConcreteCityStats::setStats().
Member Data Documentation
observers
std::vector<CityObserver*> CityStats::observers private
Collection of registered observers.
Definition at line 19 of file CityStats.h.
Referenced by attach(), detach(), and notify().
The documentation for this class was generated from the following file:
CityStats.h