City Simulation: BuildingTax Class Reference
BuildingTax Class Reference
Concrete strategy for calculating building taxes.
#include <BuildingTax.h>
Public Member Functions
BuildingTax ()=default
~BuildingTax () override=default
double calculateTax (double amount) override
Calculate tax for a building.
double calculateTotalTax ()
Calculate total tax for all buildings.
Public Member Functions inherited from TaxStrategy
virtual ~TaxStrategy ()=default
Virtual destructor for proper cleanup of derived classes.
Detailed Description
Concrete strategy for calculating building taxes.
Implements TaxStrategy for building-specific tax calculations
See also
TaxStrategy
Building
Definition at line 19 of file BuildingTax.h.
Constructor & Destructor Documentation
BuildingTax()
BuildingTax::BuildingTax () default
~BuildingTax()
BuildingTax::~BuildingTax () override default
Member Function Documentation
calculateTax()
double BuildingTax::calculateTax (double amount) override virtual
Calculate tax for a building.
Parameters
amount Base amount for tax calculation
Returns
double Calculated tax amount
Implements TaxStrategy.
Definition at line 5 of file BuildingTax.cpp.
{
     if (amount < 10000)
         return amount * 0.001;
     else if (amount < 20000)
         return amount * 0.002;
     else if (amount < 30000)
         return amount * 0.003;
     else if (amount < 40000)
         return amount * 0.004;
     else if (amount < 50000)
         return amount * 0.005;
     else if (amount < 60000)
         return amount * 0.006;
     else if (amount < 70000)
         return amount * 0.007;
     else if (amount < 80000)
         return amount * 0.008;
     else if (amount < 90000)
         return amount * 0.009;
     else if (amount < 100000)
         return amount * 0.10;
     else
         return amount * 0.11;
 }
Referenced by Building::calculateTax(), and calculateTotalTax().
calculateTotalTax()
double BuildingTax::calculateTotalTax ()
Calculate total tax for all buildings.
Returns
double Total tax amount
Definition at line 30 of file BuildingTax.cpp.
{
     double totalTax = 0.0;
     std::vector<Building*> buildingsCopy = Building::buildings;
     for (Building* building : buildingsCopy) {
         if (building) {  // Check if pointer is valid
             totalTax += calculateTax(building->getCost());
         }
     }
     return totalTax;
 }
References Building::buildings, and calculateTax().
Referenced by Building::calculateTotalTax().
The documentation for this class was generated from the following files:
BuildingTax.h
BuildingTax.cpp