City Simulation: IncomeTax Class Reference
IncomeTax Class Reference
Class implementing income tax calculation strategy.
#include <IncomeTax.h>
Public Member Functions
IncomeTax ()=default
Default constructor.
~IncomeTax () override=default
Virtual destructor.
double calculateTax (double amount) override
Calculates tax for a given amount.
double calculateTotalTax ()
Calculates the total tax.
Public Member Functions inherited from TaxStrategy
virtual ~TaxStrategy ()=default
Virtual destructor for proper cleanup of derived classes.
Detailed Description
Class implementing income tax calculation strategy.
This class provides functionality for calculating income tax as a concrete implementation of the TaxStrategy interface.
Definition at line 15 of file IncomeTax.h.
Constructor & Destructor Documentation
IncomeTax()
IncomeTax::IncomeTax () default
Default constructor.
~IncomeTax()
IncomeTax::~IncomeTax () override default
Virtual destructor.
Member Function Documentation
calculateTax()
double IncomeTax::calculateTax (double amount) override virtual
Calculates tax for a given amount.
Parameters
amount The amount to calculate tax on
Returns
The calculated tax amount
Implements TaxStrategy.
Definition at line 4 of file IncomeTax.cpp.
{
     if (amount < 10000)
         return amount * 0.10;
     else if (amount < 20000)
         return amount * 0.11;
     else if (amount < 30000)
         return amount * 0.12;
     else if (amount < 40000)
         return amount * 0.14;
     else if (amount < 50000)
         return amount * 0.15;
     else if (amount < 60000)
         return amount * 0.16;
     else if (amount < 70000)
         return amount * 0.17;
     else if (amount < 80000)
         return amount * 0.18;
     else if (amount < 90000)
         return amount * 0.19;
     else if (amount < 100000)
         return amount * 0.20;
     else
         return amount * 0.25;
 }
Referenced by CitizenPrototype::calculateTax(), and calculateTotalTax().
calculateTotalTax()
double IncomeTax::calculateTotalTax ()
Calculates the total tax.
Returns
The total tax amount
Definition at line 28 of file IncomeTax.cpp.
{
     double totalTax = 0.0;
     for (CitizenPrototype* citizen : CitizenPrototype::citizens) {
         totalTax += calculateTax(citizen->getSalary());
     }
     return totalTax;
 }
References calculateTax(), and CitizenPrototype::citizens.
Referenced by CitizenPrototype::calculateTotalTax().
The documentation for this class was generated from the following files:
IncomeTax.h
IncomeTax.cpp