City Simulation: UtilityNetwork Class Reference
UtilityNetwork Class Reference
Represents a utility network infrastructure system @inherits Infrastructure.
#include <UtilityNetwork.h>
Public Member Functions
UtilityNetwork ()
Default constructor initializing an empty utility network.
void setDescription (const std::string &desc) override
Sets the description of the utility network.
std::string getDescription () const override
Gets the description of the utility network.
double getCost () const override
Gets the cost of the utility network.
void setCost (double value) override
Sets the cost of the utility network.
std::string getType () const override
Gets the type of infrastructure.
bool isValid () const override
Checks if the utility network is valid.
Infrastructure * clone () const override
Creates a deep copy of the utility network.
void setCompleted (bool completed)
Sets the completion status of the network.
bool getCompleted () const
Gets the completion status of the network.
void displayInfo () const override
Displays detailed information about the utility network.
Public Member Functions inherited from Infrastructure
virtual ~Infrastructure ()=default
Virtual destructor.
Private Attributes
std::string description
double cost
bool isCompleted
Detailed Description
Represents a utility network infrastructure system @inherits Infrastructure.
This class manages utility network infrastructure, including its description, cost, completion status, and various operations for maintaining and displaying network information.
Definition at line 20 of file UtilityNetwork.h.
Constructor & Destructor Documentation
UtilityNetwork()
UtilityNetwork::UtilityNetwork () inline
Default constructor initializing an empty utility network.
Definition at line 30 of file UtilityNetwork.h.
 : description(""), cost(0.0), isCompleted(false) {}
Referenced by clone().
Member Function Documentation
clone()
Infrastructure* UtilityNetwork::clone () const inline override virtual
Creates a deep copy of the utility network.
Returns
Infrastructure* Pointer to the cloned network
Implements Infrastructure.
Definition at line 74 of file UtilityNetwork.h.
{
         UtilityNetwork* copy = new UtilityNetwork();
         copy->description = this->description;
         copy->cost = this->cost;
         copy->isCompleted = this->isCompleted;
         return copy;
     }
References cost, description, isCompleted, and UtilityNetwork().
Referenced by testIntegratedSystem().
displayInfo()
void UtilityNetwork::displayInfo () const inline override virtual
Displays detailed information about the utility network.
Outputs formatted information including type, description, cost, completion status, and validation status.
Implements Infrastructure.
Definition at line 100 of file UtilityNetwork.h.
{
         std::cout << "\n=== Utility Network Infrastructure ===" << std::endl
                   << "Type: " << getType() << std::endl
                   << "Description: " << description << std::endl
                   << "Cost: $" << std::fixed << std::setprecision(2) << cost << std::endl
                   << "Status: " << (isCompleted ? "Completed" : "In Progress") << std::endl
                   << "Validation: " << (isValid() ? "Valid" : "Invalid") << std::endl;
     }
References cost, description, getType(), isCompleted, and isValid().
getCompleted()
bool UtilityNetwork::getCompleted () const inline
Gets the completion status of the network.
Returns
bool True if the network is completed
Definition at line 92 of file UtilityNetwork.h.
 { return isCompleted; }
References isCompleted.
getCost()
double UtilityNetwork::getCost () const inline override virtual
Gets the cost of the utility network.
Returns
double The current cost
Implements Infrastructure.
Definition at line 48 of file UtilityNetwork.h.
 { return cost; }
References cost.
getDescription()
std::string UtilityNetwork::getDescription () const inline override virtual
Gets the description of the utility network.
Returns
std::string The current description
Implements Infrastructure.
Definition at line 42 of file UtilityNetwork.h.
 { return description; }
References description.
getType()
std::string UtilityNetwork::getType () const inline override virtual
Gets the type of infrastructure.
Returns
std::string The string "UtilityNetwork"
Implements Infrastructure.
Definition at line 60 of file UtilityNetwork.h.
 { return "UtilityNetwork"; }
Referenced by displayInfo().
isValid()
bool UtilityNetwork::isValid () const inline override virtual
Checks if the utility network is valid.
Returns
bool True if the network has a description and positive cost
Implements Infrastructure.
Definition at line 66 of file UtilityNetwork.h.
{
         return !description.empty() && cost > 0;
     }
References cost, and description.
Referenced by displayInfo().
setCompleted()
void UtilityNetwork::setCompleted (bool completed) inline
Sets the completion status of the network.
Parameters
completed The completion status to set
Definition at line 86 of file UtilityNetwork.h.
 { isCompleted = completed; }
References isCompleted.
setCost()
void UtilityNetwork::setCost (double value) inline override virtual
Sets the cost of the utility network.
Parameters
value The cost to set
Implements Infrastructure.
Definition at line 54 of file UtilityNetwork.h.
 { cost = value; }
References cost.
setDescription()
void UtilityNetwork::setDescription (const std::string & desc) inline override virtual
Sets the description of the utility network.
Parameters
desc The description to set
Implements Infrastructure.
Definition at line 36 of file UtilityNetwork.h.
 { description = desc; }
References description.
Member Data Documentation
cost
double UtilityNetwork::cost private
Cost of the utility network
Definition at line 23 of file UtilityNetwork.h.
Referenced by clone(), displayInfo(), getCost(), isValid(), and setCost().
description
std::string UtilityNetwork::description private
Description of the utility network
Definition at line 22 of file UtilityNetwork.h.
Referenced by clone(), displayInfo(), getDescription(), isValid(), and setDescription().
isCompleted
bool UtilityNetwork::isCompleted private
Completion status of the network
Definition at line 24 of file UtilityNetwork.h.
Referenced by clone(), displayInfo(), getCompleted(), and setCompleted().
The documentation for this class was generated from the following file:
UtilityNetwork.h