City Simulation: TransportSystemAdapter Class Reference
TransportSystemAdapter Class Reference
Adapts a LegacyTransportSystem to work with the ModernTransport interface @inherits ModernTransport.
#include <TransportSystemAdapter.h>
Public Member Functions
TransportSystemAdapter (LegacyTransportSystem *system)
Construct a new Transport System Adapter.
~TransportSystemAdapter ()
Destructor.
std::string operationModernTransport () override
Adapts the legacy transport operation to modern format.
int getPassengerCapacity () const override
Gets the passenger capacity from legacy system.
double getFuelEfficiency () const override
Gets the fuel efficiency from legacy system.
std::string getTransportType () const override
Gets the transport type from legacy system.
double getMaintenanceCost () const override
Gets the maintenance cost from legacy system.
bool isOperational () const override
Checks if the legacy system is operational.
void updateLegacySystem ()
Updates the legacy system attributes.
bool hasLegacySystem () const
Checks if a legacy system is connected.
Public Member Functions inherited from ModernTransport
ModernTransport ()
Default constructor.
virtual ~ModernTransport ()
Virtual destructor.
Private Member Functions
void updateModernAttributes ()
Updates the modern attributes from the legacy system.
Private Attributes
LegacyTransportSystem * legacySystem
Additional Inherited Members
Protected Attributes inherited from ModernTransport
int passengerCapacity
double fuelEfficiency
std::string transportType
double maintenanceCost
bool operational
Detailed Description
Adapts a LegacyTransportSystem to work with the ModernTransport interface @inherits ModernTransport.
Definition at line 15 of file TransportSystemAdapter.h.
Constructor & Destructor Documentation
TransportSystemAdapter()
TransportSystemAdapter::TransportSystemAdapter (LegacyTransportSystem * system) inline
Construct a new Transport System Adapter.
Parameters
system Pointer to legacy transport system to adapt
Note
Does not take ownership of the passed system
Definition at line 22 of file TransportSystemAdapter.h.
                                                           : legacySystem(system) {
         if (legacySystem) {
             updateModernAttributes();
         }
     }
References legacySystem, and updateModernAttributes().
~TransportSystemAdapter()
TransportSystemAdapter::~TransportSystemAdapter () inline
Destructor.
Note
Does not delete the legacy system as we don't own it
Definition at line 32 of file TransportSystemAdapter.h.
{
         // Note: We don't delete legacySystem here as we don't own it
     }
Member Function Documentation
getFuelEfficiency()
double TransportSystemAdapter::getFuelEfficiency () const inline override virtual
Gets the fuel efficiency from legacy system.
Returns
double The fuel efficiency in km per liter @override
Reimplemented from ModernTransport.
Definition at line 67 of file TransportSystemAdapter.h.
{
         if (legacySystem) {
             // Convert liters per 100km to km per liter
             float oldUsage = legacySystem->getOldFuelUsage();
             return (oldUsage > 0) ? (100.0 / oldUsage) : 0.0;
         }
         return 0.0;
     }
References LegacyTransportSystem::getOldFuelUsage(), and legacySystem.
Referenced by testTransportSystemAdaptation().
getMaintenanceCost()
double TransportSystemAdapter::getMaintenanceCost () const inline override virtual
Gets the maintenance cost from legacy system.
Returns
double The maintenance cost, 0.0 if no legacy system @override
Reimplemented from ModernTransport.
Definition at line 93 of file TransportSystemAdapter.h.
{
         if (legacySystem) {
             // Convert legacy repair costs to maintenance cost format
             return static_cast<double>(legacySystem->getRepairCosts()) * 1.1; // 10% overhead for adaptation
         }
         return 0.0;
     }
References LegacyTransportSystem::getRepairCosts(), and legacySystem.
Referenced by testTransportSystemAdaptation().
getPassengerCapacity()
int TransportSystemAdapter::getPassengerCapacity () const inline override virtual
Gets the passenger capacity from legacy system.
Returns
int The passenger capacity, 0 if no legacy system @override
Reimplemented from ModernTransport.
Definition at line 55 of file TransportSystemAdapter.h.
{
         if (legacySystem) {
             return legacySystem->getOldCapacity();
         }
         return 0;
     }
References LegacyTransportSystem::getOldCapacity(), and legacySystem.
Referenced by testTransportSystemAdaptation().
getTransportType()
std::string TransportSystemAdapter::getTransportType () const inline override virtual
Gets the transport type from legacy system.
Returns
std::string The transport type, "Unknown" if no legacy system @override
Reimplemented from ModernTransport.
Definition at line 81 of file TransportSystemAdapter.h.
{
         if (legacySystem) {
             return std::string("Adapted ") + legacySystem->getVehicleClass();
         }
         return "Unknown";
     }
References LegacyTransportSystem::getVehicleClass(), and legacySystem.
Referenced by testTransportSystemAdaptation().
hasLegacySystem()
bool TransportSystemAdapter::hasLegacySystem () const inline
Checks if a legacy system is connected.
Returns
bool True if connected, false otherwise
Definition at line 127 of file TransportSystemAdapter.h.
{
         return legacySystem != nullptr;
     }
References legacySystem.
isOperational()
bool TransportSystemAdapter::isOperational () const inline override virtual
Checks if the legacy system is operational.
Returns
bool True if operational, false otherwise @override
Reimplemented from ModernTransport.
Definition at line 106 of file TransportSystemAdapter.h.
{
         if (legacySystem) {
             return legacySystem->getServiceStatus() == 1;
         }
         return false;
     }
References LegacyTransportSystem::getServiceStatus(), and legacySystem.
Referenced by testTransportSystemAdaptation().
operationModernTransport()
std::string TransportSystemAdapter::operationModernTransport () inline override virtual
Adapts the legacy transport operation to modern format.
Returns
std::string The adapted transport operation message @override
Reimplemented from ModernTransport.
Definition at line 41 of file TransportSystemAdapter.h.
{
         if (legacySystem) {
             // Adapt the legacy operation to modern format
             std::string legacyOperation = legacySystem->operateOldTransport();
             return "Adapted Transport Operation: " + legacyOperation;
         }
         return "No Legacy System Connected";
     }
References legacySystem, and LegacyTransportSystem::operateOldTransport().
Referenced by testTransportSystemAdaptation().
updateLegacySystem()
void TransportSystemAdapter::updateLegacySystem () inline
Updates the legacy system attributes.
Definition at line 117 of file TransportSystemAdapter.h.
{
         if (legacySystem) {
             updateModernAttributes();
         }
     }
References legacySystem, and updateModernAttributes().
updateModernAttributes()
void TransportSystemAdapter::updateModernAttributes () inline private
Updates the modern attributes from the legacy system.
Definition at line 137 of file TransportSystemAdapter.h.
{
         passengerCapacity = legacySystem->getOldCapacity();
         fuelEfficiency = 100.0 / legacySystem->getOldFuelUsage();
         transportType = std::string("Adapted ") + legacySystem->getVehicleClass();
         maintenanceCost = static_cast<double>(legacySystem->getRepairCosts());
         operational = (legacySystem->getServiceStatus() == 1);
     }
References ModernTransport::fuelEfficiency, LegacyTransportSystem::getOldCapacity(), LegacyTransportSystem::getOldFuelUsage(), LegacyTransportSystem::getRepairCosts(), LegacyTransportSystem::getServiceStatus(), LegacyTransportSystem::getVehicleClass(), legacySystem, ModernTransport::maintenanceCost, ModernTransport::operational, ModernTransport::passengerCapacity, and ModernTransport::transportType.
Referenced by TransportSystemAdapter(), and updateLegacySystem().
Member Data Documentation
legacySystem
LegacyTransportSystem* TransportSystemAdapter::legacySystem private
Definition at line 132 of file TransportSystemAdapter.h.
Referenced by getFuelEfficiency(), getMaintenanceCost(), getPassengerCapacity(), getTransportType(), hasLegacySystem(), isOperational(), operationModernTransport(), TransportSystemAdapter(), updateLegacySystem(), and updateModernAttributes().
The documentation for this class was generated from the following file:
TransportSystemAdapter.h