City Simulation: TaxSystem Class Reference
TaxSystem Class Reference
Implements the Strategy pattern for tax calculations.
#include <TaxSystem.h>
Public Member Functions
TaxSystem (TaxStrategy *strategy)
Constructor that initializes the tax system with a strategy.
~TaxSystem ()
Destructor that ensures proper cleanup of the strategy.
void setStrategy (TaxStrategy *newStrategy)
Changes the current tax calculation strategy.
double calculateTax (double amount)
Calculates tax using the current strategy.
Private Attributes
TaxStrategy * strategy
Detailed Description
Implements the Strategy pattern for tax calculations.
This class manages different tax calculation strategies and delegates the actual tax computation to the current strategy.
Definition at line 16 of file TaxSystem.h.
Constructor & Destructor Documentation
TaxSystem()
TaxSystem::TaxSystem (TaxStrategy * strategy) inline
Constructor that initializes the tax system with a strategy.
Parameters
strategy Pointer to the initial tax calculation strategy
Definition at line 25 of file TaxSystem.h.
 : strategy(strategy) {}
~TaxSystem()
TaxSystem::~TaxSystem () inline
Destructor that ensures proper cleanup of the strategy.
Definition at line 30 of file TaxSystem.h.
                  {
         delete strategy;
     }
References strategy.
Member Function Documentation
calculateTax()
double TaxSystem::calculateTax (double amount) inline
Calculates tax using the current strategy.
Parameters
amount The base amount to calculate tax on
Returns
double The calculated tax amount
Definition at line 48 of file TaxSystem.h.
{
         return strategy->calculateTax(amount);
     }
References TaxStrategy::calculateTax(), and strategy.
Referenced by testBuildingTaxSystem(), and testIncomeTaxSystem().
setStrategy()
void TaxSystem::setStrategy (TaxStrategy * newStrategy) inline
Changes the current tax calculation strategy.
Parameters
newStrategy Pointer to the new tax calculation strategy
Definition at line 38 of file TaxSystem.h.
{
         delete strategy;
         strategy = newStrategy;
     }
References strategy.
Member Data Documentation
strategy
TaxStrategy* TaxSystem::strategy private
Current tax calculation strategy
Definition at line 18 of file TaxSystem.h.
Referenced by calculateTax(), setStrategy(), and ~TaxSystem().
The documentation for this class was generated from the following file:
TaxSystem.h