City Simulation: TransportFactory Class Reference
TransportFactory Class Reference
Creates and manages transport system instances.
#include <TransportFactory.h>
Static Public Member Functions
static ModernTransport * createTransport (const std::string &type)
Create a new transport system.
static ModernTransport * adaptLegacyTransport (LegacyTransportSystem *legacySystem)
Adapt a legacy transport system to modern format.
static void cleanup ()
Clean up all legacy transport systems.
Static Private Attributes
static std::vector< LegacyTransportSystem * > legacySystems
Collection of legacy transport systems.
Detailed Description
Creates and manages transport system instances.
Implements factory pattern for transport system creation
See also
ModernTransport
LegacyTransportSystem
Definition at line 20 of file TransportFactory.h.
Member Function Documentation
adaptLegacyTransport()
static ModernTransport* TransportFactory::adaptLegacyTransport (LegacyTransportSystem * legacySystem) inline static
Adapt a legacy transport system to modern format.
Parameters
legacySystem Legacy transport system to adapt
Returns
ModernTransport* Pointer to adapted transport system
Definition at line 49 of file TransportFactory.h.
{
         if (legacySystem) {
             return new TransportSystemAdapter(legacySystem);
         }
         return nullptr;
     }
Referenced by CityPlanner::adaptLegacyTransport().
cleanup()
static void TransportFactory::cleanup () inline static
Clean up all legacy transport systems.
Definition at line 59 of file TransportFactory.h.
{
         for (auto* system : legacySystems) {
             delete system;
         }
         legacySystems.clear();
     }
References legacySystems.
Referenced by testTransportSystemAdaptation().
createTransport()
static ModernTransport* TransportFactory::createTransport (const std::string & type) inline static
Create a new transport system.
Parameters
type Type of transport system to create
Returns
ModernTransport* Pointer to new transport system
Definition at line 33 of file TransportFactory.h.
{
         if (type == "modern") {
             return new ModernTransport();
         } else if (type == "legacy") {
             LegacyTransportSystem* legacySystem = new LegacyTransportSystem();
             legacySystems.push_back(legacySystem);
             return new TransportSystemAdapter(legacySystem);
         }
         return nullptr;
     }
References legacySystems.
Referenced by CityPlanner::integrateTransportSystem(), and testTransportSystemAdaptation().
Member Data Documentation
legacySystems
std::vector< LegacyTransportSystem * > TransportFactory::legacySystems static private
Collection of legacy transport systems.
Definition at line 25 of file TransportFactory.h.
Referenced by cleanup(), and createTransport().
The documentation for this class was generated from the following file:
TransportFactory.h