City Simulation: EnergyEfficiencyUpgrade Class Reference
EnergyEfficiencyUpgrade Class Reference
Handles energy efficiency upgrades for buildings.
#include <EnergyEfficiencyUpgrade.h>
Public Member Functions
EnergyEfficiencyUpgrade (Building *building)
Constructor.
void applyUpgrade ()
Applies an energy efficiency upgrade to the building.
double getUpgradeCost () const override
Calculates the cost of the next upgrade.
Public Member Functions inherited from BuildingUpgrade
BuildingUpgrade (Building *building)
Constructs a BuildingUpgrade decorator around an existing Building.
virtual ~BuildingUpgrade () override
Virtual destructor.
std::string getDescription () const override
Gets the building's description.
double getCost () const override
Gets the building's cost.
std::string getBuildingType () const override
Gets the building's type.
double getFloorArea () const override
Gets the building's floor area.
int getMaxCapacity () const override
Gets the building's maximum capacity.
void setMaxCapacity (int capacity) override
void add (CityComponent *component) override
Adds a child component.
void remove (CityComponent *component) override
Removes a child component.
int getUpgradeLevel () const
void incrementUpgradeLevel ()
Public Member Functions inherited from Building
virtual double calculateTax () const
virtual double calculateTotalTax () const
Building (const std::string &name, double area, int capacity, double cost)
virtual ~Building ()
void setCost (long double cost)
void print (int indent=0) const override
Prints the component details.
void incrementOccupancy ()
void upgradeSecurity ()
void upgradeEnergyEfficiency ()
void upgradeCapacity ()
void setSecurityLevel (int level)
void setEnergyLevel (int level)
void setCapacityLevel (int level)
int getSecurityLevel () const
int getEnergyLevel () const
int getCapacityLevel () const
void setState (BuildingState *newState)
std::string getState () const
std::string getName () const override
Gets the component name.
void setParentNeighborhood (Neighborhood *neighborhood)
Neighborhood * getParentNeighborhood () const
double getResourceRequirement (const std::string &resourceType) const
void receiveResource (const std::string &resource, int amount) override
Receive resource allocation.
int getResourceLevel (const std::string &resource) const override
Get current resource level.
bool needsResource (const std::string &resource) const override
Check if resource is needed.
void setResourceRequirement (const std::string &resource, int amount)
Public Member Functions inherited from CityComponent
virtual ~CityComponent ()=default
Virtual destructor.
virtual double getPopulation () const
Gets the component population.
virtual double getArea () const
Gets the component area.
virtual std::vector< CityComponent * > getComponents () const
Gets child components.
virtual CityComponent * findComponent (const std::string &name)
Finds a component by name.
Public Member Functions inherited from BaseBuilding
virtual ~BaseBuilding ()=default
Virtual destructor.
Public Member Functions inherited from ResourceConsumer
virtual ~ResourceConsumer ()=default
Virtual destructor.
Additional Inherited Members
Static Public Member Functions inherited from Building
static void cleanup ()
Static Public Attributes inherited from Building
static std::vector< Building * > buildings
Protected Attributes inherited from BuildingUpgrade
Building * building
int upgradeLevel
Protected Attributes inherited from Building
std::string buildingType
std::string name
double floorArea
int maxCapacity
int currentOccupancy = 0
bool maintenanceNeeded
double energyUsage
long double Cost
int securityLevel = 1
int capacityLevel = 1
int energyLevel = 1
Neighborhood * parentNeighborhood
std::unordered_map< std::string, int > resourceLevels
Protected Attributes inherited from CityComponent
double population = 0.0
Component population.
double area = 0.0
Component area.
Detailed Description
Handles energy efficiency upgrades for buildings.
Implements the upgrade system for building energy efficiency with 5 levels
Definition at line 11 of file EnergyEfficiencyUpgrade.h.
Constructor & Destructor Documentation
EnergyEfficiencyUpgrade()
EnergyEfficiencyUpgrade::EnergyEfficiencyUpgrade (Building * building) inline explicit
Constructor.
Parameters
building Pointer to the building to be upgraded
Definition at line 17 of file EnergyEfficiencyUpgrade.h.
         : BuildingUpgrade(building) {
         // Set initial upgradeLevel based on building's current level
         upgradeLevel = building->getEnergyLevel();
     }
References BuildingUpgrade::building, Building::getEnergyLevel(), and BuildingUpgrade::upgradeLevel.
Member Function Documentation
applyUpgrade()
void EnergyEfficiencyUpgrade::applyUpgrade () inline
Applies an energy efficiency upgrade to the building.
Increases energy efficiency level if not at maximum (level 5)
Definition at line 27 of file EnergyEfficiencyUpgrade.h.
{
         if (upgradeLevel < 5) {  // Check current level
             double upgradeCost = getUpgradeCost();
             building->setCost(building->getCost() + upgradeCost);
             upgradeLevel++;  // Increment first
             building->setEnergyLevel(upgradeLevel);  // Then set new level
             std::cout << "Energy efficiency upgraded to level " << upgradeLevel << "\n";
         } else {
             std::cout << "Maximum energy efficiency level reached (5)\n";
         }
     }
References BuildingUpgrade::building, Building::getCost(), getUpgradeCost(), Building::setCost(), Building::setEnergyLevel(), and BuildingUpgrade::upgradeLevel.
Referenced by testBuildingUpgrades(), and Building::upgradeEnergyEfficiency().
getUpgradeCost()
double EnergyEfficiencyUpgrade::getUpgradeCost () const inline override virtual
Calculates the cost of the next upgrade.
Returns
Cost of the next upgrade level
Reimplemented from BuildingUpgrade.
Definition at line 43 of file EnergyEfficiencyUpgrade.h.
{
         return 3000 * (upgradeLevel + 1); // Cost for next level
     }
References BuildingUpgrade::upgradeLevel.
Referenced by applyUpgrade().
The documentation for this class was generated from the following file:
EnergyEfficiencyUpgrade.h