City Simulation: CityResourceDistribution Class Reference
CityResourceDistribution Class Reference
Singleton class managing resource distribution across the city.
#include <CityResourceDistribution.h>
Public Member Functions
CityResourceDistribution (const CityResourceDistribution &)=delete
CityResourceDistribution & operator= (const CityResourceDistribution &)=delete
void cleanup ()
void registerUtility (const std::string &name, UtilitySystem *system) override
Register new utility system.
void registerBuilding (Building *building)
void distributeResources (const std::string &name, const std::string &resource, int amount) override
Distribute resources to utilities.
double getTotalResources () const
double getResourceAmount (const std::string &resource) const
size_t getUtilityCount () const
size_t getBuildingCount () const
Public Member Functions inherited from ResourceDistributor
virtual ~ResourceDistributor ()=default
Virtual destructor.
Static Public Member Functions
static CityResourceDistribution * getInstance ()
static void destroyInstance ()
Private Member Functions
CityResourceDistribution ()
~CityResourceDistribution ()
Private Attributes
std::unordered_map< std::string, UtilitySystem * > utilities
std::vector< Building * > buildings
std::unordered_map< std::string, double > totalResources
bool isBeingDestroyed
Static Private Attributes
static CityResourceDistribution * instance = nullptr
Detailed Description
Singleton class managing resource distribution across the city.
Handles registration and distribution of resources between utilities and buildings
See also
ResourceDistributor
Building
UtilitySystem
Definition at line 23 of file CityResourceDistribution.h.
Constructor & Destructor Documentation
CityResourceDistribution() [1/2]
CityResourceDistribution::CityResourceDistribution () inline private
Definition at line 32 of file CityResourceDistribution.h.
 : isBeingDestroyed(false) {}
Referenced by getInstance().
~CityResourceDistribution()
CityResourceDistribution::~CityResourceDistribution () inline private
Definition at line 35 of file CityResourceDistribution.h.
{
         if (!isBeingDestroyed) {
             cleanup();
         }
     }
References cleanup(), and isBeingDestroyed.
CityResourceDistribution() [2/2]
CityResourceDistribution::CityResourceDistribution (const CityResourceDistribution &) delete
Member Function Documentation
cleanup()
void CityResourceDistribution::cleanup () inline
Definition at line 60 of file CityResourceDistribution.h.
                    {
         if (isBeingDestroyed) return;
         isBeingDestroyed = true;
         // Clear utilities first
         utilities.clear();
         // Clear other containers
         buildings.clear();
         totalResources.clear();
         isBeingDestroyed = false;
     }
References buildings, isBeingDestroyed, totalResources, and utilities.
Referenced by destroyInstance(), main(), and ~CityResourceDistribution().
destroyInstance()
static void CityResourceDistribution::destroyInstance () inline static
Definition at line 52 of file CityResourceDistribution.h.
{
         if (instance) {
             instance->cleanup();
             delete instance;
             instance = nullptr;
         }
     }
References cleanup(), and instance.
Referenced by main(), and testMediatorPattern().
distributeResources()
void CityResourceDistribution::distributeResources (const std::string & name, const std::string & resource, int amount) inline override virtual
Distribute resources to utilities.
Parameters
name Target utility name
resource Resource type
amount Resource quantity
Implements ResourceDistributor.
Definition at line 85 of file CityResourceDistribution.h.
{
         // Validate input
         if (amount <= 0) {
             std::cout << "Warning: Invalid resource amount " << amount << "\n";
             return;
         }
         // First check if utility exists and can process the resource
         auto utilityIt = utilities.find(name);
         if (utilityIt == utilities.end() || !utilityIt->second->canProcessResource(resource)) {
             std::cout << "Warning: Invalid utility or resource type\n";
             return;
         }
         // Count buildings that need this resource
         std::vector<Building*> needyBuildings;
         for (Building* building : buildings) {
             if (building && building->needsResource(resource)) {
                 needyBuildings.push_back(building);
             }
         }
         if (needyBuildings.empty()) {
             std::cout << "No buildings currently need " << resource << "\n";
             return;
         }
         // Update utility's resource level
         utilityIt->second->receiveResources(resource, amount);
         totalResources[resource] += amount;
         // Calculate distribution amount per building
         int sharePerBuilding = amount / needyBuildings.size();
         // Distribute to buildings
         std::cout << "\nDistributing " << sharePerBuilding << " units of " << resource
                   << " to each of " << needyBuildings.size() << " buildings\n";
         for (Building* building : needyBuildings) {
             building->receiveResource(resource, sharePerBuilding);
             std::cout << "Distributed to " << building->getName()
                       << " - New level: " << building->getResourceLevel(resource) << "\n";
         }
     }
References buildings, totalResources, and utilities.
Referenced by testMediatorPattern().
getBuildingCount()
size_t CityResourceDistribution::getBuildingCount () const inline
Definition at line 148 of file CityResourceDistribution.h.
{
         return buildings.size();
     }
References buildings.
Referenced by testMediatorPattern().
getInstance()
static CityResourceDistribution* CityResourceDistribution::getInstance () inline static
Definition at line 45 of file CityResourceDistribution.h.
{
         if (!instance) {
             instance = new CityResourceDistribution();
         }
         return instance;
     }
References CityResourceDistribution(), and instance.
Referenced by ConcreteBuildingFactory::createBuilding(), main(), and testMediatorPattern().
getResourceAmount()
double CityResourceDistribution::getResourceAmount (const std::string & resource) const inline
Definition at line 138 of file CityResourceDistribution.h.
{
         auto it = totalResources.find(resource);
         return (it != totalResources.end()) ? it->second : 0.0;
     }
References totalResources.
Referenced by testMediatorPattern().
getTotalResources()
double CityResourceDistribution::getTotalResources () const inline
Definition at line 130 of file CityResourceDistribution.h.
{
         double total = 0.0;
         for (const auto& [_, amount] : totalResources) {
             total += amount;
         }
         return total;
     }
References totalResources.
Referenced by ResourceConsumption::update().
getUtilityCount()
size_t CityResourceDistribution::getUtilityCount () const inline
Definition at line 144 of file CityResourceDistribution.h.
{
         return utilities.size();
     }
References utilities.
operator=()
CityResourceDistribution& CityResourceDistribution::operator= (const CityResourceDistribution &) delete
registerBuilding()
void CityResourceDistribution::registerBuilding (Building * building) inline
Definition at line 79 of file CityResourceDistribution.h.
{
         if (building && std::find(buildings.begin(), buildings.end(), building) == buildings.end()) {
             buildings.push_back(building);
         }
     }
References buildings.
Referenced by ConcreteBuildingFactory::createBuilding(), and testMediatorPattern().
registerUtility()
void CityResourceDistribution::registerUtility (const std::string & name, UtilitySystem * system) inline override virtual
Register new utility system.
Parameters
name Utility system identifier
system Pointer to utility system
Implements ResourceDistributor.
Definition at line 74 of file CityResourceDistribution.h.
{
         if (!system || isBeingDestroyed) return;
         utilities[name] = system; // Store pointer only
     }
References isBeingDestroyed, and utilities.
Referenced by testMediatorPattern().
Member Data Documentation
buildings
std::vector<Building*> CityResourceDistribution::buildings private
Definition at line 26 of file CityResourceDistribution.h.
Referenced by cleanup(), distributeResources(), getBuildingCount(), and registerBuilding().
instance
CityResourceDistribution * CityResourceDistribution::instance = nullptr static private
Definition at line 28 of file CityResourceDistribution.h.
Referenced by destroyInstance(), and getInstance().
isBeingDestroyed
bool CityResourceDistribution::isBeingDestroyed private
Definition at line 29 of file CityResourceDistribution.h.
Referenced by cleanup(), registerUtility(), and ~CityResourceDistribution().
totalResources
std::unordered_map<std::string, double> CityResourceDistribution::totalResources private
Definition at line 27 of file CityResourceDistribution.h.
Referenced by cleanup(), distributeResources(), getResourceAmount(), and getTotalResources().
utilities
std::unordered_map<std::string, UtilitySystem*> CityResourceDistribution::utilities private
Definition at line 25 of file CityResourceDistribution.h.
Referenced by cleanup(), distributeResources(), getUtilityCount(), and registerUtility().
The documentation for this class was generated from the following file:
CityResourceDistribution.h