City Simulation: Worker Class Reference
Worker Class Reference
Represents working citizens in the city.
#include <Worker.h>
Public Member Functions
Worker (int id, double salary)
Constructor.
~Worker () override=default
Destructor.
Worker (const Worker &other)
Copy constructor.
CitizenPrototype * clone () const override
Clone the worker.
const std::string getRole () const override
Get the role of the worker.
void performTask () override
Perform the worker's task.
Public Member Functions inherited from CitizenPrototype
CitizenPrototype (int id, double salary)
Constructor.
virtual ~CitizenPrototype ()
Virtual destructor.
CitizenPrototype (const CitizenPrototype &other)
Copy constructor.
virtual double calculateTotalTax () const
virtual double calculateTax () const
int getID () const
void setID (int newID)
double getSalary () const
virtual void setSalary (double newSalary)
void setBuilding (Building *b)
Building * getBuilding () const
double getSatisfaction () const
void updateSatisfaction (double newSatisfaction)
Additional Inherited Members
Static Public Member Functions inherited from CitizenPrototype
static int getCitizenCount ()
static void cleanup ()
Static Public Attributes inherited from CitizenPrototype
static std::vector< CitizenPrototype * > citizens
static int citizenCount = 0
Protected Member Functions inherited from CitizenPrototype
CitizenPrototype & operator= (const CitizenPrototype &other)
Protected Attributes inherited from CitizenPrototype
int id
Citizen identification number.
double salary
Citizen's salary or income.
double satisfaction
Citizen's satisfaction level.
Building * building
Building where citizen is located.
IncomeTax * incomeTax
Tax calculator for citizen.
Detailed Description
Represents working citizens in the city.
Implements worker-specific behaviors and attributes
See also
CitizenPrototype
Definition at line 16 of file Worker.h.
Constructor & Destructor Documentation
Worker() [1/2]
Worker::Worker (int id, double salary) inline
Constructor.
Parameters
id Citizen identification number
salary Initial salary
Definition at line 23 of file Worker.h.
 : CitizenPrototype(id, salary) {}
Referenced by clone().
~Worker()
Worker::~Worker () override default
Destructor.
Worker() [2/2]
Worker::Worker (const Worker & other) inline
Copy constructor.
Parameters
other Worker to copy
Definition at line 34 of file Worker.h.
 : CitizenPrototype(other) {}
Member Function Documentation
clone()
CitizenPrototype* Worker::clone () const inline override virtual
Clone the worker.
Returns
Worker* Copy of the worker
Implements CitizenPrototype.
Definition at line 40 of file Worker.h.
{
         return new Worker(*this);
     }
References Worker().
getRole()
const std::string Worker::getRole () const inline override virtual
Get the role of the worker.
Returns
std::string Role of the worker
Implements CitizenPrototype.
Definition at line 48 of file Worker.h.
{
         return "Worker";
     }
performTask()
void Worker::performTask () inline override virtual
Perform the worker's task.
Implements CitizenPrototype.
Definition at line 55 of file Worker.h.
{
         std::cout << "Worker #" << getID() << " is working";
         if (getBuilding()) {
             std::cout << " in the ";
             getBuilding()->print();
         }
         std::cout << "\n";
     }
References CitizenPrototype::getBuilding(), CitizenPrototype::getID(), and Building::print().
The documentation for this class was generated from the following file:
Worker.h