City Simulation: Infrastructure Class Reference
Infrastructure Class Reference abstract
Abstract base class for infrastructure components.
#include <Infrastructure.h>
Public Member Functions
virtual ~Infrastructure ()=default
Virtual destructor.
virtual void setDescription (const std::string &desc)=0
Sets the infrastructure description.
virtual std::string getDescription () const =0
Gets the infrastructure description.
virtual double getCost () const =0
Gets the infrastructure cost.
virtual void setCost (double cost)=0
Sets the infrastructure cost.
virtual std::string getType () const =0
Gets the infrastructure type.
virtual Infrastructure * clone () const =0
Creates a clone of the infrastructure.
virtual bool isValid () const =0
Checks if the infrastructure is valid.
virtual void displayInfo () const =0
Displays information about the infrastructure.
Detailed Description
Abstract base class for infrastructure components.
This class defines the interface for all infrastructure components in the system, providing methods for description, cost management, type identification, and validation.
Definition at line 13 of file Infrastructure.h.
Constructor & Destructor Documentation
~Infrastructure()
virtual Infrastructure::~Infrastructure () virtual default
Virtual destructor.
Member Function Documentation
clone()
virtual Infrastructure* Infrastructure::clone () const pure virtual
Creates a clone of the infrastructure.
Returns
Pointer to the cloned Infrastructure object
Implemented in UtilityNetwork, RoadNetwork, and PublicTransit.
displayInfo()
virtual void Infrastructure::displayInfo () const pure virtual
Displays information about the infrastructure.
Implemented in UtilityNetwork, RoadNetwork, and PublicTransit.
Referenced by testIntegratedSystem().
getCost()
virtual double Infrastructure::getCost () const pure virtual
Gets the infrastructure cost.
Returns
The cost as a double
Implemented in UtilityNetwork, RoadNetwork, and PublicTransit.
Referenced by PublicTransitBuilder::BuildFinishing(), RoadNetworkBuilder::BuildFinishing(), UtilityNetworkBuilder::BuildFinishing(), PublicTransitBuilder::BuildStructure(), RoadNetworkBuilder::BuildStructure(), and UtilityNetworkBuilder::BuildStructure().
getDescription()
virtual std::string Infrastructure::getDescription () const pure virtual
Gets the infrastructure description.
Returns
String containing the description
Implemented in UtilityNetwork, RoadNetwork, and PublicTransit.
Referenced by PublicTransitBuilder::BuildFinishing(), RoadNetworkBuilder::BuildFinishing(), UtilityNetworkBuilder::BuildFinishing(), PublicTransitBuilder::BuildStructure(), RoadNetworkBuilder::BuildStructure(), and UtilityNetworkBuilder::BuildStructure().
getType()
virtual std::string Infrastructure::getType () const pure virtual
Gets the infrastructure type.
Returns
String containing the type
Implemented in UtilityNetwork, RoadNetwork, and PublicTransit.
isValid()
virtual bool Infrastructure::isValid () const pure virtual
Checks if the infrastructure is valid.
Returns
true if valid, false otherwise
Implemented in UtilityNetwork, RoadNetwork, and PublicTransit.
Referenced by PublicTransitBuilder::isValidBuild(), RoadNetworkBuilder::isValidBuild(), and UtilityNetworkBuilder::isValidBuild().
setCost()
virtual void Infrastructure::setCost (double cost) pure virtual
Sets the infrastructure cost.
Parameters
cost The new cost
Implemented in UtilityNetwork, RoadNetwork, and PublicTransit.
Referenced by PublicTransitBuilder::BuildFinishing(), RoadNetworkBuilder::BuildFinishing(), UtilityNetworkBuilder::BuildFinishing(), PublicTransitBuilder::BuildFoundation(), RoadNetworkBuilder::BuildFoundation(), UtilityNetworkBuilder::BuildFoundation(), PublicTransitBuilder::BuildStructure(), RoadNetworkBuilder::BuildStructure(), and UtilityNetworkBuilder::BuildStructure().
setDescription()
virtual void Infrastructure::setDescription (const std::string & desc) pure virtual
Sets the infrastructure description.
Parameters
desc The new description
Implemented in UtilityNetwork, RoadNetwork, and PublicTransit.
Referenced by PublicTransitBuilder::BuildFinishing(), RoadNetworkBuilder::BuildFinishing(), UtilityNetworkBuilder::BuildFinishing(), PublicTransitBuilder::BuildFoundation(), RoadNetworkBuilder::BuildFoundation(), UtilityNetworkBuilder::BuildFoundation(), PublicTransitBuilder::BuildStructure(), RoadNetworkBuilder::BuildStructure(), and UtilityNetworkBuilder::BuildStructure().
The documentation for this class was generated from the following file:
Infrastructure.h